### ISSUE TITLE
Interface - Icon passt nicht

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#10]
Bitte überprüfen in welcher .ini Datei das steht. Irgendwie fehlen Icons.
http://metadev.linuxx.org/Record/66498fmt

**Comment by patrick-heiss** [comment]
Das Problem liegt daran, dass beim Ausführen von "sudo ~/meta/deploy.sh" die "metadev-config.ini" mit "alten" Werten ausgeführt wurde. Jetzt habe ich die Werte im Git eingecheckt. Bitte nochmal probieren.

**Comment by marius300482** [comment]
Ich habe gerade das deployskript laufen lassen. Diesesmal ist alles erhalten geblieben.

**Comment by marius300482** [comment]
check mal das: http://metadev.linuxx.org/Record/20372fmt
bei mir ohne icon.

**Comment by patrick-heiss** [comment]
Bei mir wird unter http://metadev.linuxx.org/Record/20372fmt das Platzhalter-Icon http://metadev.linuxx.org/Cover/Show?size=large& angezeigt, da offenbar kein Cover-Bild vorliegt. Ist das falsch?

**Comment by marius300482** [comment]
jetzt geht es auch bei mir wieder. ups.
