### ISSUE TITLE
System - Uploadtool Fragen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#101]
Hallo Robert,

ich habe vorhin die Datei neu.xml.zip hochgeladen. Hat auch alles geklappt aber die alten Dateneinträge wurden nicht vorher gelöscht. Woran liegt das?

Neuer Datensatz - siehe Datum
http://metadev.linuxx.org/Record/1885ash

Älterer noch vorhandener Datensatz - siehe Datum
http://metadev.linuxx.org/Record/2746ash

LG Marius

**Comment by rproutermedia** [comment]
Hallo Marius,
Christoph hat sich das Problem angeschaut und bestätigt, dass vom Uploadtool kein Lösch-Kommando abgesetzt wird. Ich bin im Moment mit einer größeren Überarbeitung des Uploadtools beschäftigt und werde mich der Sache annehmen.

Grüße
Robert

**Comment by marius300482** [comment]
Hallo Robert,

vielen Dank für die schnelle Antwort und die Bearbeitung des Problems!

Viele Grüße,
Marius

**Comment by rproutermedia** [comment]
Hallo Marius,

alte Einträge werden beim Upload einer neuen Version jetzt tatsächlich gelöscht.

Grüße
Robert

**Comment by marius300482** [comment]
Ich muss hier nochmal nachfragen. Habe die Daten der ASH hochgeladen und die Fotografien (die von mir entfernt wurden) werden noch immer angezeigt. Hängt da was im Cache? 

Darüber hinaus werden Informationen, die in der transformierten Datei angezeigt werden nicht im Katalog angezeigt.

Bsp. http://metadev.linuxx.org/Record/6910ash
'&lt;reviewer&gt;Morgenthaler, Barbara; Kosmann, Marianne&lt;/reviewer&gt;'

Woran kann das liegen?

**Comment by rproutermedia** [comment]
Hallo Marius,
ich möchte mir die unterschiedlichen Dateien gerne ansehen. Im Archiv sehe ich im Moment jeweils nur eine Version. Bitte lade einmal einen alten und einen neuen Stand hoch (jeweils 2 Stände werden momentan archiviert) und teile mir mit, welches Dokument nicht gelöscht wurde, obwohl es im neuen Stand nicht mehr vorkommt.

Grüße
Robert

**Comment by rproutermedia** [comment]
Alternativ die beiden Dateien per Mail an rpr@outermedia

**Comment by marius300482** [comment]
Ich die andere Datei auch nicht mehr da. Die letzte Datei, die im Archiv ist sollte die aktuellste sein. Kannst du denn sehen ob ein delete vorgenommen wurde?

Ich habe das auch gerade nochmal für Helene Lange Archiv probiert. Auch hier gibt es keinen delete. Die Daten liegen jetzt doppelt vor.

**Comment by rproutermedia** [comment]
Laut Logdatei des Uploadtools wurden zuvor alle Dokumente des HeleneLangeArchiv aus Solr gelöscht. Leider kann ich Löschungen im Solr-Log im Moment nicht einsehen. Ich sehe mir jetzt mal die Daten in Solr an.

**Comment by rproutermedia** [comment]
Ich habe mir die Dokumente im Solr-Index angesehen und festgestellt, dass für einige Institutionen ungültige IDs verwendet wurden, z.B. 
falsch: <institution>Kölner Frauengeschichtsverein</institution> 
richtig: <institution>KoelnerFrauengeschichtsverein</institution>
Die IDs der Institutionen enthalten weder Umlaute noch Leerzeichen! Beim Löschen der alten Version werden die IDs des Uploadtools verwendet und somit keine zu löschenden Dokumente für den Kölner Frauengeschichtsverein oder das Helene Lange Archiv gefunden. Bitte verwende als Werte für <institution> nur die Schreibungen im "Library/Archive" Pull-Down-Menü auf der Upload-Site.
Um die Dokumente mit ungültigen IDs zu entfernen, wird es nötig sein, muss ggf. der gesamten Solr-Index gelöscht werden.

**Comment by marius300482** [comment]
Wie versprochen hier nochmal der Sachverhalt. Die id eines Datensatzes wird um ein Institutionskürzel erweitert. Hier: 'genderbib'. Das steht in diesem Feld hier:
&lt;field name="id"&gt;12345genderbib&lt;/field&gt; 

Mein delete Statement auf meinem lokalen System lautet
`curl http://localhost:8080/solr/biblio/update?stream.body='<delete><query>id:*genderbib</query></delete>'&commit=true`

Auf der Grundlage dieser Endungen sollen bitte die Ausschnitte aus dem Core vorgenommen werden. Nicht die Institutionsnamen.
LG Marius

**Comment by rproutermedia** [comment]
Dazu noch 2 Anmerkungen:
1. Im Moment kommen die als Dokument-ID-Endungen realisierten Institutionskürzel noch nicht in der ida-beans.xml vor und stimmen auch nicht immer mit der Bean-ID überein (bean id="frauenmediaturm" aber "fmt"-Kürzel)
2. das Löschen über "id:*genderbib" ist zwar möglich, aber bei einem großen Index nicht sehr performant, da Solr bei Queries mit * am Anfang i.d.R. alle Einträge durchsuchen muss.

Daher mein Vorschlag: Wir führen basierend auf dem Institutionskürzel ein neues Feld "institution-id" ein, welches dann durchgängig in der ida-beans.xml, dem Uploadtool und in den Dokumenten verwendet wird.

**Comment by marius300482** [comment]
Okay, das klingt vernünftig. Ich habe das Feld "institutionID" genannt und baue es bei allen Einrichtungen in die Umwandlungroutine ein. Du musst mir dann nur noch sagen, wo genau das in die bean eingetragen werden muss.

**Comment by marius300482** [comment]
Kannst du mir bitte ein delete statement basteln. das oben angegebene funktioniert nur auf meiner lokalen Maschine. Ich lösche dann manuell bevor ich neu einspiele. Vielen Dank!

**Comment by rproutermedia** [comment]
Da die Beans das neue Feld noch nicht unterstützen, ist es jetzt noch nicht sinnvoll, die Kürzel in die ida-beans.xml einzutragen. Ich werde das Uploadtool in den nächsten Tagen anpassen und brauche dafür nur eine Liste der Institutionskürzel.

Der einzige Unterschied auf dem Server ist der abweichende Name des Solr-Cores: metadev.
Per ssh auf dem Server löschst du Institutionen mittels:
`curl http://localhost:8080/solr/metadev/update?stream.body='<delete><query>id:*KÜRZEL</query></delete>'&commit=true`
oder den gesamten Index mittels:
`curl http://localhost:8080/solr/metadev/update?stream.body='<delete><query>*:*</query></delete>'&commit=true`

**Comment by marius300482** [comment]
Hier die Abkürzungen:

Genderbibliothek = genderbib
FrauenMediaTurm = fmt
STICHWORT = stichwort
Frauensolidarität = frso
FFBIZ = ffbiz
Cid Fraen an Gender = cid
belladonna = belladonna
Spinnboden = spinnboden
schema f = schemaf
GrauZone = grauzone
Alice Salomon Archiv = ash
Louise-Otto-Peters-Archiv = lopa
Helene-Lange-Archiv = hla
Kölner Frauengeschichtsverein = kfgv

LG Marius

**Comment by marius300482** [comment]
Ich habe den ersten delete-statement-Vorschlag von dir ausprobiert aber es hat leider nicht funktionieren wollen. Es wurde ein Prozess angelegt aber ich kann nicht erkennen, dass irgendwas passiert. Kannst du das bitte mal ausprobieren. LG Marius

**Comment by rproutermedia** [comment]
Das Uploadtool verwendet jetzt die institutionID für das Archiv und zum Löschen von Dokumenten in Solr.
