### ISSUE TITLE
Interface - verrutschtes Element

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#102]
Hallo Patrick,

hier ist leider etwas verrutscht.

![auswahl_177](https://cloud.githubusercontent.com/assets/7677191/7343392/a4cc318e-ecb0-11e4-8869-43a9e981e735.png)

**Comment by patrick-heiss** [comment]
Erledigt!

Sorry, dass war ein mini-CSS Fehler, der mir im Firefox nicht angezeigt wurde. Sollte jetzt passen.

**Comment by marius300482** [comment]
wunderbar
