### ISSUE TITLE
Interface - gefördert durch [...] fehlt

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#103]
Hallo Patrick,

wir brauchen auf der Seite noch den Hinweis, dass das Projekt vom Bundesministerium gefördert wird. Kannst du es bitte mit dem Text "Gefördert durch:" in den Footer einbauen.

![bmfsfj-logo](https://cloud.githubusercontent.com/assets/7677191/7346269/2fa44a2e-eccc-11e4-8430-798f58600919.png)

**Comment by patrick-heiss** [comment]
OK, ich halte dafür nochmal Rücksüpache mir Eva, was die Größe und Positionierung im Footer angeht.

**Comment by marius300482** [comment]
Wunderbar. Vielen Dank!

**Comment by marius300482** [comment]
#bump wie sieht es hier aus? Irgendwelche Rückmeldungen von Eva?

**Comment by marius300482** [comment]
Dieses Issue hat inzwischen eine gewisse Dringlichkeit. Könntest du dich hier als erstes drum kümmern? LG Marius

**Comment by patrick-heiss** [comment]
Erledigt!

**Comment by marius300482** [comment]
wunderbar!
