### ISSUE TITLE
Interface - Link aus Institutionskachel

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#104]
Hallo Patrick,

in den Institutionskacheln habe ich einen Fehler entdeckt, den ich leider nicht selber beheben kann. Der Link funktioniert nicht. 
Guckst du hier http://metadev.linuxx.org/Record/18856addf_es und probierst unten den "Zur Webseite" Link.

LG Marius

**Comment by patrick-heiss** [comment]
Das ist ein Konfigurationsfehler. Bitte entferne den / vor der URL.

Falsch:
<a href="/http://www.ida-dachverband.de
Richtig:
<a href="http://www.ida-dachverband.de
