### ISSUE TITLE
Interface - description.phtml Zeilenumbrüche

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#106]
Hallo Patrick,

im Feld description soll ein Umbruch <br/> möglich sein. Was muss ich hierfür tun? Wir das break escaped?

LG Marius

**Comment by patrick-heiss** [comment]
Ja, es wird escaped in description.phtml Zeile 461:
<?= $this->escapeHtml($description) ?>

So kannst du den Text ausgeben, wie er ist, aber dadruch kann ungültiges HTML entstehen und jede Form von HTML ist erlaubt (schlecht):
<?= $description; ?>

Mit der folgenden HTML-Funktion kannst du alle HTML-Tags, bis auf <br> entfernen, aber es kann immer noch ungültiges HTML durch Zeichen wie das kaufmännische & entstehen (besser):
<?= strip_tags($description, "<br>"); ?>

Damit kann kein ungültiges HTML entstehen und <br> is erlaubt (gut):
<?= str_replace(array("&lt;br&gt;"), array("<br />"), $this->escapeHtml($description)); ?>

Damit kann kein ungültiges HTML entstehen und <br> und  <br/> und <br /> sind erlaubt (gut):
<?= preg_replace('/&lt;br\s*\/?&gt;/i', '<br />', $this->escapeHtml($description)); ?>

Gibt es noch mehrere ähnliche Stellen? Dann schreibe ich einen eigenen Handeler dafür. (perfekt)

**Comment by marius300482** [comment]
gucke ich mir nachher gleich mal an und gebe dir Rückmeldung.

**Comment by patrick-heiss** [comment]
Erledigt!

Ich habe einen view Hanler erstellt und damir das Problem löst. Einfach "$this->escapeHtml" durch "$this->escapeHtmlAllowBr" an allen anderen den Stellen ersetzen, wo <br>s nicht escaped werden sollen.

**Comment by marius300482** [comment]
Wunderbar. Hat sehr gut geklappt.
