### ISSUE TITLE
Interface - Sternchen stehen lassen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#107]
Bitte folge mal dem Link und dann deaktiviere die Institution. Man landet unweigerlich auf der Fehlerseite. Was können wir hier tun?

http://metadev.linuxx.org/Search/Results?type=AllFields&filter%5B%5D=institution%3A%22Genderbibliothek%22

LG Marius

**Comment by patrick-heiss** [comment]
Es handelt sich um eine leere Suche, sobald die Institution bei o.g. Link entfernt wird. Bei leeren Suchen leiten wir standardmäßig auf eine Fehlerseite um.

Diesen Standard können wir natürlich nach Belieben ändern. Wir könnten z.B:
- Auf die Startseite umleiten
- Eine neue Seite für leere Suchen entwerfen
- Die letzte Suche erneut ausführen
- Eine beliebige Suche ausführen
-usw.

**Comment by marius300482** [comment]
Letzte suche ausführen klingt doch gut. Kannst du das mal probieren? Vielen Dank.

**Comment by patrick-heiss** [comment]
OK, werde ich einbauen.

**Comment by marius300482** [comment]
Vielen Dank!

**Comment by patrick-heiss** [comment]
Erledigt!

Jetzt wird automatisch die letzte erfolgreiche Suche geladen, wenn es eine gibt. Damit sollten normale Benutzer die Fehlerseite nicht mehr zu Gesicht bekommen.

**Comment by marius300482** [comment]
probiere mal hier die Institution abzuwählen. Bei mir funktioniert es leider nicht:

http://metadev.linuxx.org/Search/Results?type=AllFields&filter%5B%5D=institution%3A%22Spinnboden%22

LG Marius

**Comment by patrick-heiss** [comment]
Das ist doch korrekt! Oder soll eine leere Suche nun doch erlaubt sein?

**Comment by marius300482** [comment]
Lieber Patrick,
du hast natürlich vollkommen recht. Das der Link eine leere Suche war, war mir offensichtlich gar nicht bewußt. Mit einem ordentlichen Suchbegriff funktioniert auch das Abwählen von Facetten.
LG Marius
