### ISSUE TITLE
System - Uploadtool Archiv mit Fehler

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#108]
Hier gibt es eine Fehlermeldung.
http://metadev.linuxx.org/meta-upload/archive

**Comment by rproutermedia** [comment]
Zwei Transformation für das "Helene Lange Archiv" ist scheinbar fehlgeschlagen sodass in den zugehörigen Verzeichnissen im Archiv nicht alle Dateien existierten. 
Ich habe die fehlerhaften Verzeichnisse gelöscht und arbeite daran, dass das nicht wieder geschieht.

**Comment by rproutermedia** [comment]
Das Archiv blendet jetzt fehlerhaft gespeicherte Institutionen und Versionen aus.
