### ISSUE TITLE
Sysstem - Nutzungsaccount für Uploadtool

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#110]
Folgende Angaben werden benötigt:

* Nutzungsname
* PW
* InstitutionsID
* Mailadresse

http://metadatenbank.pbworks.com/w/page/91013766/Uploadtool

**Comment by rproutermedia** [comment]
Update: Ein Nutzungsname kann jetzt mehreren Institutionen zugewiesen werden. Es ist in diesem Fall also nicht notwendig, mehrere Accounts für dieselbe Person anzulegen.
