### ISSUE TITLE
Interface - Karte in Institutionskachel - Lila Punkt statt Textfeld

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#113]
In der Institutionskachel soll die Kartendarstellung angepasst werden. Es soll wie auf der Startseite ein Lila Punkt gezeigt werden (siehe Screenshot).

![auswahl_183](https://cloud.githubusercontent.com/assets/7677191/7607613/4d498a16-f952-11e4-84d8-0a7db3380b8b.png)

Der derzeitige Textkasten soll weichen. Die Adresse steht ja bereits in dieser Kachel drin. 

![auswahl_182](https://cloud.githubusercontent.com/assets/7677191/7607591/2d82f758-f952-11e4-87ab-7f3a9986a450.png)

**Comment by chboehm** [comment]
Klick führt jetzt auf Google Maps
