### ISSUE TITLE
Interface - "alle beteiligten Personen" Paginierung Alphabet

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#114]
Die Funktion "alle beteiligten Personen" funktioniert hervorragend. Eine Paginierung nach Alphabet würde die Sache allerdings abrunden und die Navigation in der Liste stark vereinfachen. 

![auswahl_184](https://cloud.githubusercontent.com/assets/7677191/7607661/c13cbd62-f952-11e4-8f42-f994da5c2820.png)

**Comment by chboehm** [comment]
Idee: Alphabetische Navigation mit Anzahl Treffer evaluieren

**Comment by rproutermedia** [comment]
Ich habe gerade einen Ansatz zur alphabetischen Paginierung hochgeladen. 
Es gibt die Möglichkeit, direkt über den Anfangsbuchstaben auf die erste entsprechende Seite zu springen. Die einzelnen Seiten sind nicht mehr nummeriert, sondern werden mit Präfixen der enthaltenen Namen beschriften (z.B. "Bi-Br"). Dies erlaubt eine feinere Navigation, sobald einmal zu einem Buchstaben gesprungen wurde.
Noch ein Kommentar zur Sortierung der Namen: Diese erfolgt bereits durch Solr und kann im Frontend nicht mehr ohne Weiteres beeinflusst werden. So wird z.B. "Ü" oder "e"(klein) durch Solr nach "Z" sortiert. Interessant sind auch die Sonderzeichen: Manche Namen beginnen mit "[", "@" oder "<".

**Comment by marius300482** [comment]
Lieber Robert,
ich finde den Ansatz gut. Sehr gut wäre er, wenn die Daten besser wären :) :+1: Bitte so lassen.
LG Marius
