### ISSUE TITLE
Interface - Suchfunktion im Kontext entfernen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#115]
Die Ansicht der Suche im Kontext soll entfernt werden.

![auswahl_185](https://cloud.githubusercontent.com/assets/7677191/7697693/74f0553a-fdf9-11e4-9ae9-0786a48b22a1.png)

**Comment by chboehm** [comment]
Kann per Konfiguration deaktiviert werden:
```
[Hierarchy]
; "Search within trees" can be disabled here if set to "false" (default = true)
search = false
```
