### ISSUE TITLE
"In" in der Zusammenfassung des Einzeltreffers soll ein Link sein

### ISSUE THREAD

**Issue by chboehm** [marius300482/meta#117]
![kontext broschuren und zeitungsausschnitte zu rechtsfragen](https://cloud.githubusercontent.com/assets/5340686/7862768/617b0a3e-0558-11e5-9737-517114c9c54b.png)

**Comment by chboehm** [comment]
Damit das funktioniert müssen sourceInfo und hierarchy_top_title den gleichen Inhalt haben.

**Comment by marius300482** [comment]
sourceInfo und hierarchy sind aber unterschiedlich. sourceInfo gibt es als Feld auch ohne Hierarchy.

kann man das nicht so machen:
link auf hierarchy_top_id wenn vorhanden und als Text des Links die sourceInfoAngabe?

**Comment by chboehm** [comment]
Ja, das geht. Allerdings ist sourceInfo ein Multivalue Field. Falls es mehrere Einträge gobt, vergleiche ich sourceInfo und hierarchy_top_title um den richtigen Record zu finden.

**Comment by marius300482** [comment]
Ja, da hast du recht. sourceInfo ist ein mutlivalued field. Ich denke aber, dass es überwiegend singleValued verwendet wird.

**Comment by chboehm** [comment]
Der hierarchy_top_title wurde nur für Artikel gesucht. Diese Einschränkung habe ich entfernt.
2d86fdc80c2cd23292ad16c37c9f0e033c7370f1
