### ISSUE TITLE
System - deploy.sh

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#12]
Nach einem deploy ist das Theme auf metadev falsch. Warum nur?

**Comment by marius300482** [comment]
Ich habe das theme in /metadev/config/vufind/config.ini händisch geändert. Bitte reparieren.

**Comment by patrick-heiss** [comment]
Das Problem liegt daran, dass beim Ausführen von "sudo ~/meta/deploy.sh" die "metadev-config.ini" mit "alten" Werten ausgeführt wurde. Jetzt habe ich die Werte im Git eingecheckt. Bitte nochmal probieren.

**Comment by marius300482** [comment]
Werde ich die Tage mal probieren. Bis dahin schließe ich diesen Thread :)
