### ISSUE TITLE
Marius bei der Google Search Console eintragen

### ISSUE THREAD

**Issue by solonair** [marius300482/meta#125]
1. Marius Google Mail bekommen
1. Marius eintragen

**Comment by chboehm** [comment]
Hallo Simon, anscheinend kannst nur du User hinzufügen. GMail-Adresse sende ich die per Mail.

**Comment by marius300482** [comment]
@solonair  Ich habe gerade gesehen, dass in der Search Console nur die Genderbibliothek eingetragen ist. Wie sieht es mit dem META-Katalog aus? LG Marius

**Comment by solonair** [comment]
Habe die Site hinzugefügt. Nun muss das angehängte File noch auf den Server gespielt werden. Der folgende Link muss dann funktionieren: http://meta-katalog.eu/google91e51fd4ef7894a4.html 

Mir danach Bescheid sagen:

[google91e51fd4ef7894a4.html.zip](https://github.com/marius300482/meta/files/86958/google91e51fd4ef7894a4.html.zip)

**Comment by marius300482** [comment]
@chboehm spielst du die Datei an die richtige Stelle? Ich bin unsicher wo genau das File hin soll.

**Comment by chboehm** [comment]
Liegt unter: 
`/usr/local/vufind2/public-meta/google91e51fd4ef7894a4.html`

**Comment by solonair** [comment]
User ist hinzugefügt.
