### ISSUE TITLE
Startseite - Verlinkung zum Bestand einiger Einrichtungen funktioniert nicht

### ISSUE THREAD

**Issue by b4seven** [marius300482/meta#129]
klickt man bei einigen Einrichtungen in der Karte auf den Link "zum Bestand" kommt man zur Suchergebnisseite mit der Nachricht "Keine Ergebnisse"
Scheint nur bei Einrichtungen aufzutreten, deren Namen aus MEHR als einem Wort bestehen
Beispiel Spinnboden funktioniert, Archiv der deutschen Frauenbewegung nicht

**Comment by chboehm** [comment]
Statt institution name muss instituition short verwendet werden.
