### ISSUE TITLE
URLs der Schlagworte und Personen in der Ergebnisliste Falsch

### ISSUE THREAD

**Issue by patrick-heiss** [marius300482/meta#13]
Klickt man in der Ergebnisliste auf eine Person oder ein Schlagwort, die zu einem Suchtreffer gehören, wird "lookfor" benutzt, was zu einer falschen Suche führt.

**Comment by marius300482** [comment]
Wer kann das korrigieren?

**Comment by patrick-heiss** [comment]
Ich :)

**Comment by patrick-heiss** [comment]
Da das Orignal- Vufind offenbar die gleiche URL Struktur für Schlagwörter verwendet, gehe ich davon aus, dass das angezeigte Ergebnis korrekt ist. Klickt man ein Schlagwort an, wird auch bei uns nach einem Schlagwort gesucht. Es wird nur nicht per Facette ausgewählt, sondern als Suchbegriff im Suchformular angezeigt. In diesem Fall ist es meines erachtens kein Bug, sondern eine leicht unterschiedliche Darstellungsweise des Suchergebnisses. Jetzt stellt sich die Frage: Soll der Standard an dieser Stelle geändern werden, oder nicht?

Beim Suchen nach einer Person wird deren Name standardmäßig ebenfalls als Schlagwort eingesetzt, worauf man häufig keine Suchergebnisse erhält. Hierbei würde man mehr Treffer erzielen, wenn man über alle Felder sucht indem man den Parameter "type=Subject" weg lässt. Ist das Ergebnis ohne den Parameter "type" zufriesenstellen.
Beispiel wenn man auf die Person "Stein, Gertraude" klickt => mit subject: 
http://metadev.linuxx.org/Search/Results?lookfor=%22Stein%2C+Gertrude%22&type=Subject
Beispiel wenn man auf die Person "Stein, Gertraude" klickt => ohne subject: 
http://metadev.linuxx.org/Search/Results?lookfor=%22Stein%2C+Gertrude%22

**Comment by marius300482** [comment]
Dieser Sachverhalt ist für mich zu kompliziert für diese Art der Kommunikation. Bitte schließe dich doch mal mit Christoph kurz. Wir hatte schon über einen ähnlichen Sachverhalt gesprochen. Dabei ging es um die Personensuche. Ansonsten würde ich dieses Thema gerne in naher Zukunft im Büro mit Christoph und dir besprechen. Ginge das?

**Comment by patrick-heiss** [comment]
Gerade habe ich mich mit Christoph abgesprochen.
Im Fall von Schlagworten soll die Auswahl in der Facette aktiviert werden.
Im Fall von Personen soll "type=Subject" als temporäre Lösung aus der URL entfernt werden, solange eine echte Personensuche nicht realisiert ist.

**Comment by marius300482** [comment]
Genau an diese Personensuche hatte ich gedacht. Hier muss noch ein Konzept erarbeitet werden.
