### ISSUE TITLE
Startseite - vielleicht interessant?: Abstand zw. Bild und Text einfügen

### ISSUE THREAD

**Issue by b4seven** [marius300482/meta#130]
Startseite - Bereich vielleicht interessant?
kleinen Abstand zwischen Bild und Textinformationen einfügen

![abstand](https://cloud.githubusercontent.com/assets/8090479/8034680/3ce35a60-0dea-11e5-99cf-6125d2487e40.png)

**Comment by marius300482** [comment]
@rproutermedia hier ist @chboehm leider nicht fertig geworden. Bitte in dem Zuge auch noch Issue #136 mitmachen. Anzeige und Funktionalität stimmen noch nicht ganz.

**Comment by marius300482** [comment]
.result .col-xs-1 {
    padding: .2em 1em 0 0; }
