### ISSUE TITLE
Katalog durchstöbern - viele Auswahlmöglichkeiten führen ins "nichts"

### ISSUE THREAD

**Issue by b4seven** [marius300482/meta#132]
- viele Auswahlmöglichkeiten liefern kein Ergebnis und als Nutzerin ist dann unklar was los ist bzw. wie es hier weitergeht
- wenn man dann doch mal eine Kombination gefunden hat und auf die Suchergebnisseite kommt, ist über der Trefferliste ein "i"-Icon eingeblendet mit dem Text "Eingeschränkt nach"
=> es passiert aber nichts wenn man darauf klickt, sollte was passieren?
![wastutdas](https://cloud.githubusercontent.com/assets/8090479/8034962/1d14cb1c-0ded-11e5-95ff-702ec0b8ad9b.png)

**Comment by marius300482** [comment]
@b4seven die Funktion "Katalog durchstöbern" ist aus dem Originalsystem und wird jetzt entfernt. Da müssten wir zu viel schrauben um das sinnvoll hinzubekommen.

Hinter das 'i'-Icon soll noch ein Tooltip. Den gibt es aber noch nicht. Das müssen wir noch nachholen.
