### ISSUE TITLE
System - Suchanfragen für Gruppierungstool

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#133]
Weiße Frauen in Bewegung
Androgynie und Feminismus 
Die friedfertige Frau
Nicht Ich: Logik, Lüge, Libido 
Das paradoxe Geschlecht 
Entstehung des feministischen Bewußtseins 
Wolff, Charlotte Bisexualität 
Die Potenz der Frau 
Damenwahl Frauenwahlrecht 
Soziale Verortung der Geschlechter 
Lust am Denken 
Frauen suchen ihre Geschichte 
Sexismus in der Schule 
Geschlechterkonstruktion in der sozialen Praxis 
zur theoretischen und institutionellen Rede vom Geschlecht 
Gender Kicks 
Frauen gegen Kolonialismus 
Der Raum des Politischen in postkolonialen 
Jäger- und Sammlerinnenlatein 
Politische Verhandlungssysteme und internationale Frauenpolitik 
Koedukation nein danke 
homoerotische Liebesaffäre 
Habermas und die Geschlechterfrage 
Habermas

**Comment by rproutermedia** [comment]
Ich habe mir die Resultate aller Anfragen angeschaut und gehe davon aus, dass sich die meisten Duplikate aus Büchern und Artikeln durch eine Gruppierung über ein Group-ID-Feld zusammenfassen lassen, welches wie folgt gebildet wird:

format title_short title_sub (author ODER editor[1] ODER puplisher[1])

Das Konstrukt am Ende ist notwendig, da nicht alle Artikel/Bücher eine Autoren- bzw Editoren-Angabe besitzen. Das erzeugte Feld wird von Satz- und Sonderzeichen sowie Groß/-Kleinschreibung bereinigt, sodass verschiedene Titel zusammengefasst werden können. 

Für den Fall, dass Wörter im Titel unterschiedliche geschrieben oder zusätzliche Wörter eingefügt wurden, werden die jeweiligen Werke jedoch nicht gruppiert. Hierbei handelt es i.d.R. um fehlerhafte Eingaben der Institutionen. Meiner Meinung nach ist es jedoch besser, Werke im Zweifelsfall nicht zu gruppieren, anstatt mit Hilfe gröberer Kriterien oder einer Ähnlichkeitssuche tatsächlich unterschiedliche Werke zusammenzufassen.
Darüber hinaus wäre es denkbar, die trotz der Gruppierung verbliebenen Duplikate zumindest manuell zu erfassen. Dazu könnten wir ein Tool bereitstellen, womit ein Werk als Duplikat eines anderen markiert werden kann und dieses ggf. in vufind integrieren.

**Comment by rproutermedia** [comment]
Die Generierung des Group-ID-Felds während der Indizierung und die Gruppierung in Solr kann ich voraussichtlich innerhalb der nächsten Woche umsetzen. Das Ergebnis der Duplikaterkennung muss dann zunächst in der Solr-Admin-Seite betrachten werden. Ich schlage vor, wir besprechen das Ergebnis anschließend zusammen und entscheiden, ob diese Lösung ausreicht.
Zusätzlich ist natürlich eine Anpassung von vufind notwendig, um die gruppierten Werke darzustellen. Zum damit verbundenen Zeitaufwand kann ich heute jedoch noch keine Aussage treffen.

Grüße
Robert

**Comment by marius300482** [comment]
Das klingt alles in allem schon mal sehr spannend. Ich würde das Ergebnis schon gerne in der nächsten Woche besprechen wollen. Dafür können am Mittwoch Mittag gerne bei Outermedia vorbei kommen.

**Comment by rproutermedia** [comment]
Hallo, 
du/ihr könnt gerne vorbei kommen, jedoch kann ich noch nicht zu 100% versprechen, dass ich bis Mittwoch fertig bin.

Grüße
Robert

**Comment by marius300482** [comment]
Dann hoffen wir das beste. Anni und ich kommen so gegen Mittag vorbei.

**Comment by rproutermedia** [comment]
Mit q=-institutionID:[* TO *] kann nach Dokumenten ohne institutionID gesucht werden.

**Comment by rproutermedia** [comment]
Ich stelle gerade fest, dass die allermeisten Dokumente leere institutionIDs besitzen: q=institutionID:""

Hier gibt es wohl einen Fehler bei der Transformation oder in der ida-beans Konfiguration des Uploadtools...

**Comment by marius300482** [comment]
ich werde im Zuge des Einspielens auf dem neuen Server die Umwandlungsschritte von meiner Seite her auch noch mal überprüfen.
