### ISSUE TITLE
System - Themenüberblick Allfieldssuche

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#134]
Im der Themenwolke auf der Startseite soll mit einem Klick auf ein Suchwort eine Allfieldssuche ausgelöst werden.

Im Moment wird hier gesucht "type=Subject"

**Comment by rproutermedia** [comment]
Ich habe mich an deine Änderungen gehalten und das jeweilige Thema nicht Anführungszeichen gesetzt. Damit werden jedoch auch Bestandteile einer Themenbezeichnugn gefunden.
Z.B. findet eines AllField-Suche nach dem Thema "Frauen und Kunst Fotografie Fotografinnen" auch Bücher mit dem Wort "Fotografie" im Titel.

**Comment by marius300482** [comment]
ja, genau so.
