### ISSUE TITLE
System - Sortierung Länderangaben Startseite

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#135]
Im Bereich "Zu den Beständen der teilnehmenden Institutionen" stehen die Länder in der Reihenfolge: Deutschland, Luxemburg, Schweiz, Österreich.

Ist es hier möglich das Österreich vor der Schweiz steht? Wegen "O" und so?

**Comment by marius300482** [comment]
In meiner mobilen Version ist noch gar nichts zu sehen.

**Comment by rproutermedia** [comment]
Wird mit dem nächsten Commit ausgerollt.
