### ISSUE TITLE
Interface - "Ähnliche Einträge" Icons fehlen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#137]
In der Sektion "Ähnliche Einträge" fehlen leider häufig Icons. Das muss mal überprüft werden:

http://metadev.linuxx.org/Record/27581ffbiz

![auswahl_199](https://cloud.githubusercontent.com/assets/7677191/8184252/ed83c0f6-142c-11e5-85e1-accaf54b9344.png)

**Comment by rproutermedia** [comment]
Die Icons werden basierend auf dem Format eines Dokuments angezeigt.
Für fehlende Icons habe zwei Ursachen gefunden: Zum einen fehlen die Icons bei Formaten vom Typ "Fotografie", "Ansichtskarte" und "Autograf". 
Zum anderen werden bei "Ähnliche Einträge" teilweise Dokumente angezeigt, die keinen Wert für "Format" enthalten, z.B.: http://meta-katalog.eu/Record/AktenGMZDRechtBRDffbiz

**Comment by marius300482** [comment]
Hier wurde ein default Icon festgelegt. Bin aber gerade nicht sicher welches das ist. Christoph könnte das wissen.

**Comment by dkuom** [comment]
Habe die o.g. Formate sowie "Buttons und Sticker", "Datenträger", "Nachlass / Vorlass" und "Plakat" nachgepflegt. Issue kann getestet werden.

**Comment by rproutermedia** [comment]
Sieht gut aus.

**Comment by dkuom** [comment]
Hallo Marius,

bist du mit dem Ergebnis zufrieden. Freue mich über jedes geschlossene Ticket. :)


VG
