### ISSUE TITLE
System - 2 neue Felder in der erweiterten Suche

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#138]
Die Felder Jahresangabe (displayPublishDate) und Heft (issue) sollen in der erweiterten Suche ebenfalls verfügbar sein.

**Comment by marius300482** [comment]
![auswahl_241](https://cloud.githubusercontent.com/assets/7677191/8591426/c7bc3dc4-2617-11e5-94d2-c926207b9efe.png)

**Comment by marius300482** [comment]
Eingefügt wurden die felder schon - jetzt müssen sie nur noch funktionieren.

**Comment by rproutermedia** [comment]
Erledigt. Die Konfiguration für "Erscheinungsjahr" zeigt auf das Feld publishDate, in den Daten kommt aber nur displayPublishDate vor.
