### ISSUE TITLE
System - Neuen Server für meta-katalog.eu einrichten

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#139]
Neuen Server einrichten für meta-katalog.eu.

**Comment by rproutermedia** [comment]
Hallo Marius,
der Server ist eingerichtet. Die Zugansdaten befinden sich im Wiki.
Achtung: Der Username für vufind ist jetzt "ida" (klein), nicht mehr "Ida". Das Passwort ist gleich geblieben.
Der zusätzliche Login vor /meta-upload wurde entfernt, dafür habe ich euch "richtige", zufällig generierte Passwörter für das Uploadtool eingerichtet (siehe wiki).
