### ISSUE TITLE
Ausgewählte Schlagworte in der mobilen Ansicht unter der Überschrift nochmal anzeigen.

### ISSUE THREAD

**Issue by patrick-heiss** [marius300482/meta#14]

**Comment by patrick-heiss** [comment]
Laut der Wireframes soll unterhalb der Suchergebnis-Überschrift in der Trefferliste nochmal stehen, welche Schlagworte usw. ausgewählt werden (wie in der ausgeblendeten Facette, die zum desektieren von getätigten EIngaben dient)

**Comment by marius300482** [comment]
Liebe Patrick, das ist ein guter Hinweis. Die Ergebnisse sollen ja eigentlich hervorgehoben werden. Beißt sich das mit dieser Reduktion der Schlagworte in der Ergebnisliste?

**Comment by patrick-heiss** [comment]
Das sollte Problemlos funktionieren. Die ausgeblendeten Schlagworte sind nur für den Benutzer unsichtbar. Im Quellcode kann man nach wie vor auf alle Daten zugreifen.

**Comment by marius300482** [comment]
Können wir diesen thread dann schließen, oder ist noch etwas offen? Vielleicht habe ich was übersehen.

**Comment by patrick-heiss** [comment]
Laut unseren Designern fehlen noch die Angaben, die ich auf dem Wireframe eingekringelt habe. Dabei handelt es sich offenbar um die vom Benutzer ausgewählten Facettenelemente.

Siehst du das auch so?

![wireframe](https://cloud.githubusercontent.com/assets/8044783/5822845/cef739d8-a0d7-11e4-877c-4b54aed287ce.png)

**Comment by marius300482** [comment]
Ja, das sehe ich auch so. Das fehlt noch.

**Comment by patrick-heiss** [comment]
Prima, dann baue ich es ein.

**Comment by patrick-heiss** [comment]
Ist eingebaut.

**Comment by marius300482** [comment]
vielen dank
