### ISSUE TITLE
Interface - QR-Code wieder sichtbar machen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#143]
Dieser ist in der description.phtml zwar angegeben, wird aber nicht angezeigt. Wir wollen den gerne wieder sichtbar machen.

![auswahl_202](https://cloud.githubusercontent.com/assets/7677191/8210102/059baebe-1500-11e5-86cf-836daba033a1.png)

**Comment by rproutermedia** [comment]
Erledigt.
