### ISSUE TITLE
System - Gruppierungstool

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#144]
Die gleichen Einträge werden gruppiert und dementsprechend in VuFind ausgegeben.

**Comment by rproutermedia** [comment]
Hallo Marius,
ich habe Dennys erste Version der Gruppierungsdarstellung in vufind auf dem neuen Server eingerichet. Eine Suche nach "Mädchen Junge" findet auf der ersten Seite zwei gruppierte Bände eines Buches. Momentan fehlt noch ein Ausschalter für die Gruppierung und die Trefferzahl oben zählt noch Duplikate mit.
Die Suche verwendet einen alten fmt Datensatz. Diesen kannst du unter /meta-upload/archive/ mit dem X löschen.

**Comment by marius300482** [comment]
Wie lauten die Zugangsdaten? Ist alles so wie auf dem alten Server? Ist das Uploadtool schon erreichbar? Antwort bitte per Mail. LG Marius
