### ISSUE TITLE
Interface - Kachel  "Auch verfügbar in anderen Institutionen"

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#146]
Die vierte Kachel "Auch verfügbar in anderen Institutionen" fehlt noch. Angaben über die Gestaltung hat Christoph.

**Comment by marius300482** [comment]
Hier unser Vorschlag für die Institutionskachel. 

![auswahl_250_snippet](https://cloud.githubusercontent.com/assets/7677191/8646602/b5c10556-2940-11e5-9436-14c4bcf5616f.png)


![auswahl_250](https://cloud.githubusercontent.com/assets/7677191/8646599/b0c81cec-2940-11e5-94d1-d9756832a171.png)

**Comment by rproutermedia** [comment]
Treffer aus anderen Institutionen werden jetzt angezeigt. 
TODO: ggf. Überschrift wiederholen (wie in der Abbildung), CSS bearbeiten

**Comment by marius300482** [comment]
Hier muss nichts mehr gemacht werden.
