### ISSUE TITLE
Interface - Verlinkung in result-list und core.phtml

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#148]
In der result-list.phtml und der core.phtml zeigt der Link bei Autorinnen / Herausgeberinnen auf das Feld allContributors. Bitte ändern in eine AllFields - Suche, wie bei den Schlagworten.

**Comment by dkuom** [comment]
Hallo Marius,

gilt das dann auch für alle anderen Autorinnen-Links? Er kommt mind. noch in der Datei description.phtml vor.

VG

**Comment by marius300482** [comment]
Hallo Denny, ja es soll auch dort gelten.

**Comment by marius300482** [comment]
Bitte überall hier ändern: result-list.phtml, core.phtml und description.phtml. Danke

**Comment by marius300482** [comment]
habe die link-author.phtml & link-editor.phtml angepasst. Jetzt zeigen die Links in die richtige Richtung.
