### ISSUE TITLE
Interface - Suchbutton in der mobilen Ansicht

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#149]
In der mobilen Ansicht ist der "Suchen" Knopf sehr groß. Ist es möglich ab einer bestimmten Bildschirmgröße eine Lupe daraus zu machen? Dann würde mehr Platz für die Eingabe sein.

![screenshot_2015-07-03-10-39-39](https://cloud.githubusercontent.com/assets/7677191/8495731/4ebe4640-215f-11e5-91d5-648010dd14d9.png)

**Comment by dkuom** [comment]
Sollte kein Problem sein. Werde ich mit Eva besprechen.

**Comment by dkuom** [comment]
Hallo Marius,

der Such-Button mit Lupe ist drin. Der Header ist insgesamt platzsparender geworden durch ein kleineres Logo und leicht verringerte Abstände. Außerdem habe ich noch ein paar kleine Unschönheiten ausgemerzt. Bitte schau dir alles an.


VG

**Comment by marius300482** [comment]
Hallo Denny,

die Überarbeitungen sehen sehr gut aus. Vielen Dank. Wir haben noch ein paar Fehler gefunden. Ich eröffne hierfür weitere Issues.

LG Marius
