### ISSUE TITLE
Interface - Sprungmarke

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#15]
Bei Auswahl eines Datensatzes wird man immer gleich auf den Kontext geleitet. Bitte ändern. Kein automatischer Sprung an dieser Stelle.

**Comment by patrick-heiss** [comment]
Erledigt!

Das automatische Scrollen (hierarchyTree.js) ist jetzt deaktiviert.

**Comment by marius300482** [comment]
Wunderbar!
