### ISSUE TITLE
System - Upload-Tool Fehler build script

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#150]
Wollte eine neue Institution hinzufügen und habe diese Fehlermeldung erhalten

Stop tomcat, requires sudo
[sudo] password for ztg_server: 
 * Stopping Tomcat servlet engine tomcat7                                                                                      [ OK ] 
Backup old war
mv: das Verschieben von »/var/lib/tomcat7/webapps/meta-upload.war“ nach »/var/lib/tomcat7/webapps/meta-upload.war.20150706-190244“ ist nicht möglich: Keine Berechtigung
Delete old webapp
Deploy package
cp: reguläre Datei »/var/lib/tomcat7/webapps/meta-upload.war“ kann nicht angelegt werden: Keine Berechtigung
Start tomcat
 * Starting Tomcat servlet engine tomcat7                                                                                      [ OK ] 
~/meta

**Comment by rproutermedia** [comment]
Erledigt, ztg_server darf jetzt in /var/lib/tomcat7 schreiben.
