### ISSUE TITLE
System - http://genderbibliothek.de/ mit Fehlfunktion

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#151]
Gerade bekommen:

"ich bekam gerade den Hinweis, dass die Suche bei GReTA nicht richtig 
läuft. Es wird immer nur ein Ergebnis der Suche angezeigt."

Das hängt wahrscheinlich mit dem Serverumzug zusammen oder?

LG Marius

**Comment by rproutermedia** [comment]
Es ist die Gruppierung im Ida-Vufind-Modul, welches auch für genderbibliothek.de genutzt wird. Wir haben die Gruppierung erstmal global ausgeschaltet, damit genderbibliothek.de wieder funktioniert.
Als nächstes muss die Gruppierung im Modull konfigurierbar gemacht und für meta-katalog.de wieder aktiviert werden.

**Comment by marius300482** [comment]
Okay, sehr gut.
