### ISSUE TITLE
System - Upload-Tool lässt Daten aus trotz Success Meldung

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#152]
Bei folgenden Einrichtungen hat es bisher nicht geklappt:

* Genderbib
* Frauensolidarität
* CID
* Stichwort
* Spinnboden

Beispieldaten hat er genommen. Die kompletten Datensätze leider nicht.

**Comment by rproutermedia** [comment]
Hallo Marius,
da ich jetzt endlich alle Fehler im Uploadtool einfange konnte ich feststellen: Dem Tomcat geht bei größeren Transformationen der Heap aus! 
Nachdem ich den Heap auf 2 GB erhöht hatte, lief die Transformation von Genderbib durch.
Achtung: die indizierten Genderbib-Datensätze besitzen keine institutionID! Passt du die Transformation bitte entsprechend an?

**Comment by marius300482** [comment]
Ich gucke mir gleich mal die Umwandlungsdatei an und lade erneut hoch, wenn ich das korrigiert habe.

**Comment by marius300482** [comment]
Ich habe die instutionsID eingefügt, commited, gepusht und wandle grad um. Ich gehe jetzt mal davon aus, dass das klappt.

**Comment by rproutermedia** [comment]
Leider fehlt auch nach der letzten Indizierung von genderbib die institutionID. Das entsprechende Feld existiert im working Format nicht.

**Comment by marius300482** [comment]
Ich glaube ich habe die Änderung vorhin auf den falschen Server deployed. Jetzt läuft gerade der Prozess für die Genderbibliohtek. Danach sollte InstitutionID mit dabei sein.
