### ISSUE TITLE
System - Gruppierung für versch. Instanzen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#154]
localhost - wird gruppiert
metadev - wird gruppiert
meta-katalog - wird nicht gruppiert.

Wäre natürlich super, wenn nur meta-katalog gruppiert wäre und alle anderen nicht.

**Comment by rproutermedia** [comment]
Ich musste die Gruppierung auf dem neuen Server global deaktivieren damit genderbibliothek.de wieder richtig funktioniert. Ich habe jetzt getrennte Moduele für genderbibliothek und meta-katalog eingerichtet und die Gruppierung auf meta-katalog wieder aktiviert.
Solange du metadev mit git pull aktualisierst, bekommst du auch alle neuen Features. Soll ich die Gruppierung dort wirklich rausnehmen?

**Comment by marius300482** [comment]
getrennte Module - sehr gut.
die Gruppierung bei metadev bitte wieder rausnehmen.

**Comment by rproutermedia** [comment]
Ich habe einen neuen Branch metadev-no-group erzeugt, in dem die Ergebnisgruppierung in vufind entfernt wurde, und diesen auf dem alten Server ausgecheckt.
Achtung: git pull / push auf dem alten Server verwendet nun immer metadev-no-group. Änderungen solltest du aber weiterhin in master vornehmen und dann nach metadev-no-group mergen. Niemals umgekehrt, also von metadev-no-group nach master mergen, sonst wird die Gruppierung auch auf meta-katalog entfernt!

**Comment by marius300482** [comment]
wie lautet denn der Befehl, wenn ich Neuerungen in metad-no-goup mergen will?

**Comment by rproutermedia** [comment]
Wenn du im branch metadev-no-group bist (auf metadev jetzt voreingestellt) genügt ein 
git pull 
gefolgt von 
git merge master

Habe ich gerade einmal auf metadev gemacht.

**Comment by marius300482** [comment]
kannst du das nochmal machen. Bei mir kam nix.

**Comment by rproutermedia** [comment]
Meinst du bei dir lokal oder auf metadev? Metadev ist up-to-date.

**Comment by rproutermedia** [comment]
Entschuldigung, ich habe an der falschen Stelle nachgeschaut. Jetzt ist metadev-no-group aktuell!
In Zukunft kannst du wenn du im Branch metadev-no-group bist gleich 
git pull origin master 
ausführen um master vom Server (origin) zu aktualisieren und in den aktuellen Branch zu mergen.
Aber niemals: git push origin master!!

**Comment by marius300482** [comment]
kannst du das nochmal machen. Bei mir kam nix.

**Comment by rproutermedia** [comment]
Ich habe den branch auf GitHub per "git push" auf metadev aktualisiert.
