### ISSUE TITLE
System - Klärung

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#155]
Wir haben eine Frage. Zwei Suchen werden ausgeführt. Einmal mit "frau" und einmal mit "frau*". Es gibt zwei verschiedene Ergebnisse.

http://metadev.linuxx.org/Search/Results?lookfor=frau%2A&type=AllFields&filter%5B%5D=topic_facet%3A%22Feminismus%22&filter%5B%5D=institution%3A%22Frauensolidarit%C3%A4t%22&filter%5B%5D=format%3A%22Buch%22&filter%5B%5D=contributor_facet%3A%22Knapp%2C+Gudrun-Axeli%22

http://metadev.linuxx.org/Search/Results?lookfor=frau&type=AllFields&filter%5B%5D=topic_facet%3A%22Feminismus%22&filter%5B%5D=institution%3A%22Frauensolidarit%C3%A4t%22&filter%5B%5D=format%3A%22Buch%22&filter%5B%5D=contributor_facet%3A%22Knapp%2C+Gudrun-Axeli%22

Das Buch das bei der Suche mit "frau*" auftaucht ist das hier:
http://metadev.linuxx.org/Record/000097406frso

Dort findet sich im Inhalt: " im Werk von Hannah Arendt * Maria Mies: Hausfrauisierung, Globalisierung, Subsistenzperspektive".

Frage: Warum wird das bei der Suche mit "frau" ohne Sternchen nicht gefunden?

LG Marius

**Comment by rproutermedia** [comment]
Bei der zweiten Anfrage wird die "Hausfrauisierung" in der Inhaltsangabe gefunden. Lasse ich mir den Treffer hervorheben, wird "Haus<em>frauisieru</em>ng" gehighlightet. Suche ich nach "frauis*", wird nur noch das zweite Dokument gefunden.

Der alleinige Term "frau" (z.B: als Suchwort) kommt im zweiten Dokument nicht vor, weswegen es bei der ersten Suche nicht gefunden wird. Das Wort "frauisierung" ist zudem zu kompliziert, als dass der Stemmer dort den Term "frau" extrahieren könnte.
Die Suche "frau*" sucht nach allen Termen, die mit "frau" beginnen. Offensichtlich wurde dabei das Wort "Haus" weggelassen. Das ist durch eine Komponente in der Textanalyse-Kette (EdgeNGramFilter) zu erklären, der u.a. zu jedem Term verschiedene Suffixe erzeugt. Dabei ist wohl der Term "frauisierung" indiziert worden, der dann wieder von "frau*" gematcht wurde.
