### ISSUE TITLE
System - Translated Facets funktioniert nicht mehr

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#156]
Die Funktion "Translated Facets" #54 funktioniert scheinbar nicht mehr.

Weiter Infos unter:
http://metadatenbank.pbworks.com/w/page/91008831/Themes
Die übersetzbaren Facetten eintragen in der Datei "/usr/local/vufind2/metadev/config/vufind/facets.ini" (Github #54):
[TranslatedFacets]
facets[] = Typ

**Comment by rproutermedia** [comment]
Hallo Marius,
aus dem Absatz im Wiki bin ich leider nicht  schlau geworden. Was genau ist der gewünschte Zustand?

**Comment by marius300482** [comment]
Es gibt eine Funktion die die Facette "Institution" übersetzt.

Aus "Genderbibliothek" wird dann automatisch zu "Genderbibliothek | Berlin" 

Die Angaben stehen in der de.ini

Besser verständlich?

**Comment by rproutermedia** [comment]
Erledigt. Die Konfiguration musste aktualisiert werden.
