### ISSUE TITLE
Interface - Verlinkung sourceInfo

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#157]
Die Verlinkung zwischen zwei Datensätzen funktioniert leider noch nicht immer zuverlässig:

Hier ist es nicht verlinkt: 
http://meta-katalog.eu/Record/13960belladonna/HierarchyTree?hierarchy=13933belladonna&recordID=13960belladonna

Hier ist es verlinkt:
http://meta-katalog.eu/Record/29896genderbib/HierarchyTree?hierarchy=29910genderbib&recordID=29896genderbib

![auswahl_242](https://cloud.githubusercontent.com/assets/7677191/8591615/0d9cd88e-2619-11e5-90b3-d97ac9c78549.png)

**Comment by rproutermedia** [comment]
Bisher wurde das Top-Element aus dem Kontextbaum mit sourceInfo vergleichen. Fall letzteres nicht vollständig ist (bei "Gute Nachrichten!" fehlte title_sub), wurde nicht verlinkt.
Ich lasse jetzt nur noch testen, ob beide Titel zumindest am Anfrang übereinstimmen.

**Comment by marius300482** [comment]
Sehr gut.
