### ISSUE TITLE
Interface - Gruppierung beim zuklappen wieder zum Ausgangsobjekt springen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#159]
Wenn ein gruppiertes Ergebnis ausgeklappt und dann unten wieder eingeklappt wird, dann springt man nicht zum Augsangs-Ausklapp-Objekt sondern bleibt in der Ergebnisliste stehen.

zuklappen...
![auswahl_244](https://cloud.githubusercontent.com/assets/7677191/8593819/b10709de-262a-11e5-9938-a740c407b9b3.png)

In the middle of nowhere...

![auswahl_245](https://cloud.githubusercontent.com/assets/7677191/8593824/b3a4591c-262a-11e5-919f-2b4248772768.png)

da will ich eigentlich wieder hin.

![auswahl_246](https://cloud.githubusercontent.com/assets/7677191/8593826/b54f4326-262a-11e5-9244-def93c6f8cce.png)

**Comment by rproutermedia** [comment]
Erledigt. Beim Schließen einer Gruppe wird zum Titel des Gruppenkopfes gesprungen.
