### ISSUE TITLE
System - Institution.ini

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#16]
Ich habe versucht eine neue Institution anzulegen FRSO_de.ini. "FRSO" steht im Feld "institution". 

* /usr/local/vufind2/module/Ida/data/institutions
* FRSO_de.ini

Leider wird die Karte für die Institution nicht angezeigt. Was habe ich falsch gemacht?

**Comment by patrick-heiss** [comment]
Die FRSO_de.ini war nicht gültig, aber das lag nicht am Namen. Die letzte Zeile wurde mit einem ’ anstatt eines ' abgeschlossen. Das falsche Apostroph fällt optisch kaum auf, aber es sorgt natürlich dafür, dass der Zend ini-Parster die Datei nicht verarbeiten kann.

**Comment by marius300482** [comment]
Und ich hatte noch versucht sorgfältig zu gucken. Danke für die Korrektur.
