### ISSUE TITLE
System - Spelling Suggestions on meta-katalog.eu not working

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#160]
Hier funktioniert es:
http://metadev.linuxx.org/Search/Results?lookfor=gender+fussball&limit=20&sort=relevance

Hier nicht:
http://meta-katalog.eu/Search/Results?lookfor=gender+fussball&limit=20&sort=relevance

**Comment by rproutermedia** [comment]
Erledigt. Ich musste noch den Solr Core auf meta-katalog optimieren, um die notwendigen Wörterbücher zu erzeugten.
Dein Beispiel mit "der fussbal" funktioniert auf meta-katalog nicht, da ich dort schon deutsche Stoppwörter (der, die, ein, weil, da, bis, ...) konfiguriert habe und "der" somit rausfällt.
Alternativ: http://meta-katalog.eu/Search/Results?lookfor=fusball&limit=20&sort=relevance

**Comment by marius300482** [comment]
wunderbar!
