### ISSUE TITLE
Interface - Überarbeitungen korrigieren

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#161]
Ich habe ein paar änderungen vorgenommen. Bitte so anpassen, dass es für alle Bildschirmgrößen passt.

https://github.com/marius300482/meta/commit/559a68fcb996957f4d36d42e1b657cda270b9d05
https://github.com/marius300482/meta/commit/e4b26744f2189baf7f12a5f4b42ddc13ce65aef2
https://github.com/marius300482/meta/commit/4f205c72198e62ae81c96b8b7e01cf02ae8884e7
https://github.com/marius300482/meta/commit/6f0392b42576f92613e6dd3406816abc9c2991cd

**Comment by marius300482** [comment]
besonders die Mobilansicht hat gelitten :)

**Comment by dkuom** [comment]
Habe die Änderungen ins SASS übernommen und ggf. korrigert. Diese sollten dann nach Eva's Urlaub (Anfang September) noch einmal mit ihr abgestimmt werden. Kann getestet werden.

**Comment by dkuom** [comment]
Hallo Marius,

wie gefällt es dir?


VG
