### ISSUE TITLE
Interface - Alle Facetten Multi-Select

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#167]
Alle Facetten sollen die gleiche Multi-Select-Funktionalität haben. Derzeitig sind nur "Suchworte" und "Beteiligte Personen" Multi-Select fähig.
Formate und Institutionen sind derzeitig Mono-Select.

**Comment by rproutermedia** [comment]
Momentan ist keine Facette als "Multi-Select" konfiguriert. 
Der Grund warum mal einige und mal alle weitere Werte einer Facette verschwinden ist in den Daten zu suchen: Es verschwinden beim Klick auf einen Wert in der Dokumenttyp- und Institutionen-Facette alle anderen Werte, da einem Dokument genau ein Format und genau eine Institution zugeordnet werden. Die Anzahl der gefundenen Dokumente mit einem nicht ausgewählten Wert ist somit immer 0.  Dagegen kann ein Dokument mehrere beteiligte Personen und Suchworte haben.
Ich könnte die Solr-Anfrage so anpassen, dass bspw beim Klick auf Institution A jeweils die Anzahl der Dokumente mit anderen Institutionen stehen bleibt (als wäre A nicht ausgewählt worden). Was soll jedoch passieren, wenn anschließend noch eine Institution B gewählt wird? Sollen dann Dokumente mit Institutionen A ODER B angezeigt werden?

**Comment by marius300482** [comment]
Du hast Recht. Das hatte ich nicht bedacht. Hier bitte nix ändern. Das ist für eine nächste Feature Runde auf dem Zettel. LG Marius

**Comment by rproutermedia** [comment]
Alles klar!
