### ISSUE TITLE
Impressum anlegen

### ISSUE THREAD

**Issue by b4seven** [marius300482/meta#168]
für den META-Katalog sollte ein eigenes Impressum angelegt werden:

neben den üblichen Infos
- Vereinsdaten
- Kontaktpersonen
- Haftungsausschlüsse

sollte im Gegensatz zum ida-Impressum noch folgendes ergänzt werden:
- Datenschutzerklärungen (piwik, Cookies)
- Outermedia als Dienstleister/verantwortlich für die Realisierung

**Comment by marius300482** [comment]
Verlinkung auf http://www.ida-dachverband.de/impressum/
