### ISSUE TITLE
Fehlerseite nicht angepasst

### ISSUE THREAD

**Issue by dkuom** [marius300482/meta#17]
http://metadev.linuxx.org/Record/29910genderbib

![image](https://cloud.githubusercontent.com/assets/8589504/5817927/2b3e8290-a0b1-11e4-8b05-7c6b58e9e680.png)

**Comment by patrick-heiss** [comment]
Die angezeigte E-Mail-Adresse steht in der metadev-config.ini Datei, Zeile 22.

**Comment by marius300482** [comment]
Habe ich geändert und gepusht.
