### ISSUE TITLE
System - RECOVERY Alert

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#170]
Ich bekomme diese Nachrichten hier. Woran liegt das und lässt es sich korrigieren.

LG Marius

RECOVERY Alert
Service: HTTP
URL: http://genderbibliothek.de/Search/Results
Name: www.genderbibliothek.de
Group Name: Default
Date/Time: 8-24-2015 04:27:47 GMT
Additional Information: HTTP OK HTTP/1.0 200 OK - 1.830 second response time. IP 141.20.139.44 
Downtime: 52 minute(s) 37 second(s)

**Comment by rproutermedia** [comment]
Der Server war offenbar für eine Weile nicht erreichbar, in den Log-Dateien konnten wir allerdings nichts Auffälliges findes. Alles OK.

**Comment by chboehm** [comment]
@marius300482 Kannst du beim Rechnerbetrieb herausfinden ob evt. das Uni-Netz nicht erreichbar war?

**Comment by marius300482** [comment]
@chboehm nein, das kann ich so leicht nicht herausbekommen. Die Fehlermeldungen kommen inzwischen relativ häufig.
