### ISSUE TITLE
System - Auflösen fehlerhafter Hierarchie bringt Server zum Erliegen

### ISSUE THREAD

**Issue by rproutermedia** [marius300482/meta#171]
In den letzten beiden Wochen ist mir immer wieder aufgefallen, dass meta-katalog zeitweise nicht antwortete, z.T. half nur noch ein Neustart von vufind. In der Log-Datei war zu beobachten, dass vufind nur noch mit der Auflösung des Hierachiebaums beschäftigt war, um den Kontext von Werken darstellen zu können. 
Ich habe mir das Phänomen heute nochmal angesehen und festgestellt, dass es sich - zumindest beim letzten Auftreten des Problems - immer um dasselbe Werk an der Spitze der Hierarchie handelte: 
http://meta-katalog.eu/Record/000000473frso
Diese Zeitschrift hat über 1900 untergeordnete Artikel! Wenn sich auch noch mehrere Anfragen zu diesen Artikeln (z.B. ausgelöst durch Bots/Webcrawler) überschneiden, bringt die Auflösung der Hierarchie (jeweils 2x ca. 1900 Anfragen) den Server zum Erliegen!

**Comment by marius300482** [comment]
Okay. Ich gucke mir das Problem in dieser Woche an. Da dachte ich wohl, dass dieser Kelch an mir vorbeigeht. Ist eine Besonderheit in den Daten.

**Comment by rproutermedia** [comment]
Ich habe den Vufind Code jetzt so angepasst, dass maximal 100 untergeordnete Werke angefragt werden. Ich gehe davon aus, dass dieser Wert von üblichen Zeitschriften nicht überschritten wird, kann ihn aber selbstverständlich noch korrigieren.

**Comment by marius300482** [comment]
Ich hatte gehofft, dass das Problem gelöst ist aber irgendwas hängt noch immer :(

![auswahl_284](https://cloud.githubusercontent.com/assets/7677191/9711423/14ef567c-5533-11e5-9c96-6a821ad8afc6.png)

**Comment by rproutermedia** [comment]
Das Problem hängt wohl nur mittelbar mit der Hierarchieauflösung zusammen. Der Aussetzer heute morgen hat vermutlich mit einer vollgelaufenen Festplatte zutun. Ich habe gerade vor allem (durch den Hierarchiebug viel zu große) Log-Dateien gelöscht, aber auch alte Kernel deinstalliert etc... und hoffe dass der Fehler jetzt nicht mehr auftritt.

**Comment by marius300482** [comment]
ich hoffe das es sich damit erledigt hat.
