### ISSUE TITLE
Interface - Mobilansicht -> Karte

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#172]
Wenn ich auf einem Datensatz bin und Standort ausklappe, ist auf Android & IPhone die Markierung nicht zu sehen. Sie ist verschoben und wird erst sichtbar wenn ich rauszoome.

Darüber hinaus funktioniert der Link nur in der Browseransicht von Maps aber nicht für die Maps-App.

**Comment by dkuom** [comment]
Hallo Marius,

beide Fehler sind behoben und können getestet werden.


VG

**Comment by marius300482** [comment]
Läuft! Danke.
