### ISSUE TITLE
Interface - mehr Platz bei der Institutionsliste

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#173]
Ich habe es für unseren Geschmack etwas leserlicher gestaltet.

https://github.com/marius300482/meta/commit/65f8abe6760096caa167bfbb91466fa02fe7b72e

Bitte aufnhemen in die SASS Datei.

**Comment by b4seven** [comment]
ist in sass-file ergänzt, css fehlt noch siehe https://github.com/chboehm/vufind-ida/issues/8
