### ISSUE TITLE
Server - Speicher - Absturz - Reboot

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#174]
Der Liveserver ist leider gerade nicht erreichbar. Ich denke, dass das mit einer Datenumwandlung zu tun hat, die ich angestoßen habe. 

Frage: Startet der irgendwann automatisch neu? 

LG Marius

**Comment by rproutermedia** [comment]
Ich komme auch per SSH nicht auf den Server. Das ähnelt der Downtime vor Kurzem. Bist du sicher, dass es nicht wieder an der HU liegt?
Für einen Neustart ohne SSH müssen wir direkt an den Server.

**Comment by marius300482** [comment]
Ich habe gerade den Neustart veranlasst. Ich denke, dass es an der Datenumwandlung liegt und nicht an der HU. Ich starte morgen eine neue Umwandlung. Vielleicht kannst du ja vorher mal in die Log-Files gucken.

**Comment by marius300482** [comment]
läuft wieder!

**Comment by marius300482** [comment]
Ich werde den Umwandlungsprozess morgen nochmal anstoßen. Es handelt sich um eine über 90MB große Datei. Würde ich gerne im Ganzen machen. Was denkst du? Wird das gehen?

**Comment by rproutermedia** [comment]
Ich habe mir die Logs angesehen und es sieht momentan nicht nach einem Problem der Datenumwandlung aus. Du kannst es gerne nochmal probieren.

**Comment by marius300482** [comment]
Die Umwandlung läuft. Mal sehen ob es klappt, oder wieder in die Knie geht.

**Comment by marius300482** [comment]
Die Umwandlung hat funktioniert. Wunderbar!
