### ISSUE TITLE
System - Logrolling für vufinddev.log und Apache error.log einrichten

### ISSUE THREAD

**Issue by rproutermedia** [marius300482/meta#176]
Die Logs von Vufind und Apache füllen die Platte regelmäßig bis zum Limit. vufinddev.log sollte automatisch gerollt, gerollte error.log Dateien regelmäßig gelöscht werden.

**Comment by marius300482** [comment]
@rproutermedia der Server ist jetzt wieder voll. Kannst du da was machen? LG Marius

**Comment by rproutermedia** [comment]
Ich habe wieder einige Logs gelöscht und das automatische Entfernen von Paketen (z.B. Kernel Images) für unattended-upgrades aktiviert.
