### ISSUE TITLE
Durchlesen der Message in der Google Search Console

### ISSUE THREAD

**Issue by solonair** [marius300482/meta#177]
Aktionsvorschläge durchlesen und Bewerten. Lohnenswerte Aktionen direkt umsetzen.

**Comment by marius300482** [comment]
@solonair wo genau finde ich die Aktionsvorschläge und wie kann ich sie direkt umsetzen?

**Comment by solonair** [comment]
In der Console unter Message gibt es einen Eintrag via E-Mail. Du solltest Dich mit Deinem Google Account anmelden können.
