### ISSUE TITLE
Interface - core.phtml + Ergebnisliste

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#18]
Folgende Angaben sollen bitte in die Anzeige genommen werden:

* Bandangabe (volume) in die Ergebnisliste mit aufnehmen & in die core.phtml einarbeiten
![auswahl_129](https://cloud.githubusercontent.com/assets/7677191/5834256/69daa09a-a153-11e4-8a4e-8b84ed28917a.png)

**Comment by patrick-heiss** [comment]
Erledigt!

Sollte das Leerzeichen vor dem Komma unbeabsichtigt sein, kann ich es noch entfernen.

![screenshot from 2015-01-21 17 51 07](https://cloud.githubusercontent.com/assets/8044783/5840501/4f951808-a196-11e4-9afe-7a378aa3cabe.png)
