### ISSUE TITLE
Interface - Tooltips

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#181]
Ich möchte gerne an verschiedenen Stellen Tooltips einbauen können. Derzeitig ist eine schnelle Lösung eingebaut. Die hätte ich gerne schöner und in folgenden Bereichen:

* Description (siehe Screenshot)
* Startseite Dokumententypen

Besser sehen die Tooltips gerade im Katalog der Genderbibliothek aus:
http://genderbibliothek.de/Record/54955genderbib

![auswahl_366](https://cloud.githubusercontent.com/assets/7677191/12476220/2c3cb03a-c028-11e5-9c4d-344ebee1938e.png)

**Comment by b4seven** [comment]
erledight
