### ISSUE TITLE
Genderbib - Kontext Browser

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#182]
Der Kontext der Genderbibliothek funktioniert nicht im Firefoxbrowser.

 http://genderbibliothek.de/Record/51735genderbib/HierarchyTree#tabnav

![auswahl_367](https://cloud.githubusercontent.com/assets/7677191/12476369/21f79986-c029-11e5-982e-e914664a6f9b.png)

**Comment by outermedia-cbo** [comment]
Im XSL war falsch auskommentiert.
