### ISSUE TITLE
Genderbib - Kommentarereiter entfernen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#183]
Die Kommentare sollen nicht genutzt werden. Der Reiter kann also weg. Leider weiß ich nicht wie.

![auswahl_367](https://cloud.githubusercontent.com/assets/7677191/12476412/71c6a9fc-c029-11e5-91de-294c3275ce4a.png)

**Comment by outermedia-cbo** [comment]
Removed `UserComments` from `recorddriver_tabs` in `module/Genderbib/config/module.config.php`.

File is NOT on github.
