### ISSUE TITLE
Interface - core.phtml Autorin vs. Herausgeberin

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#20]
Hier bitte wie in der Ergebnisliste. Wenn keine Autorin (author) dann die Herausgeberin (editor) angeben. Nicht beide siehe: http://metadev.linuxx.org/Record/000073924frso

**Comment by patrick-heiss** [comment]
Ist erledigt!

**Comment by marius300482** [comment]
hier sieht es noch anders aus: http://metadev.linuxx.org/Record/64641fmt
bitte überprüfen

**Comment by patrick-heiss** [comment]
Ach sorry! Ich hatte übersehen, dass die Herausgeberinnen auf der Seite 2x genannt werden können. Jetztsind beide Stellen angepasst.
