### ISSUE TITLE
Feature - Personensuche

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#21]
Müssen wir uns mal mit auseinandersetzen.

**Comment by patrick-heiss** [comment]
Bitte überprüft bei dieser Gelegenheit auch sämtliche Links, die in der "core.phtml" bzw. "description.phtml" generiert werden. Bei einer Suche nach "Personen", "Land", "Quellenangabe", "Schriftenreihe" usw. wird in der Regel eine Schlagwortsuche gestartet und die führt wiederum sehr häufig zu einem leeren Suchergebnis. Daher sollte idealerweise für jeden Link festgelegt werden, wie die Suchanfrage aussehen soll.
