### ISSUE TITLE
Interface - Facette EDITOR

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#22]
Wo genau lässt sich das ändern? EDITOR soll HERAUSGEGEBEN VON werden.

![auswahl_131](https://cloud.githubusercontent.com/assets/7677191/5838058/5675e98c-a17c-11e4-9b14-9c245e457c7c.png)

**Comment by patrick-heiss** [comment]
Das geht über die facets.ini und die liegt unter "/usr/local/vufind2/config/vufind/facets.ini"
Jede Facette entspricht einer Zeile, die sich aus dem Namen des zugehörigen Solr-Feldes und dem Schlüssel aus der Sprachdatei (siehe z.B. unsere de.ini) zusammensetzt.

Die Facette für Schlagworte ist z.B. die Zeile:
topic_facet        = Subjects

Ich ändere das mal eben.

**Comment by marius300482** [comment]
Hätte ich wissen können ☺
