### ISSUE TITLE
System - Hierarchy > ich finde den Fehler nicht

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#23]
Hier funktioniert der Kontext nicht:
http://metadev.linuxx.org/Record/000096954frso

<field name="hierarchy_top_id">000067560frso</field>
<field name="hierarchy_top_title">Feminist review</field>
<field name="hierarchy_parent_id">000067560frso</field>
<field name="hierarchy_parent_title">Feminist review</field>
<field name="is_hierarchy_id">000096954frso</field>
<field name="is_hierarchy_title">Ukraine'''s ancient matriarch as a topos in constructing a feminine identity</field>

Im übergeordneten Datensatz schon:
http://metadev.linuxx.org/Record/000067560frso 

Wo genau liegt hier der Hase im Pfeffer?

**Comment by dkuom** [comment]
Hallo Marius,

da ich diese Records nicht in meinem lokalen Index habe, würde ich dich zunächt bitten zu überprüfen, dass es sich dabei nicht um einen typischen Fall von Caching handelt. Die XML-Repräsentation jedes Kontextbaums wird unter vufind/local/cache/hierarchy/ zwischengespeichert. U.u. liegt in diesem Fall noch eine veraltete Datei vor.

VG

**Comment by dkuom** [comment]
Okay, habe mit Patrick's Hilfe jetzt den aktuellen Index installiert und gehe der Sache jetzt weiter auf den Grund. EIn Caching-Problem ist es dann wohl nicht.

**Comment by dkuom** [comment]
Für die Bestimmung der Eltern-Elemente u.s.w. nutze ich eine Funktion, die auf das Feld "hierarchy_sequence" eines Eintrags zugreift. Leider existiert dieses Feld für "000096954frso" nicht. Für "000067560frso" übrigens ebenso nicht. Wenn es im Baum nicht "weiter aufwärts geht", dann ermittle ich noch die unmittelbaren Kindelemente, falls der berechnete Baum noch leer ist (s. Fix von letzter Woche). Aus diesem Grund entsteht bei "000067560frso" überhaupt eine Hierachie. Kannst du etwas zu dem fehlenden Feld sagen?

**Comment by marius300482** [comment]
das ist eine sehr interessante Information. Ich wusste noch nicht, dass diese Angabe so entscheidend ist. Ich werde das zu den Datensätzen mal hinzufügen und morgen auch noch mehr dazu schreiben. Bin gerade in einer Sitzung.

**Comment by marius300482** [comment]
Ich achte ab jetzt drauf die hierarchy_sequenz mit hinzuzunehmen. Jetzt funktioniert es: http://metadev.linuxx.org/Record/000096954frso
