### ISSUE TITLE
Interface - sourceInfo in core.phtml verfügbar machen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#24]
Das Feld sourceInfo muss eingebaut werden. Bitte unter die Verlagsangaben packen.

Ob es da bleibt ist fraglich aber für den Anfang kann es dort hin.

**Comment by patrick-heiss** [comment]
Ist erledigt.

Die sourceInfo wird nun unterhalb der Verlagsangaben angezeigt. Da die Verlagsinformationen nicht unter "Weitere Informationen" vorkommen, bin ich davon ausgegangen, dass sie nur oben in der core.phtml vorkommen und auch nicht in der Suchliste.

![sourceinfo](https://cloud.githubusercontent.com/assets/8044783/5876783/5e30fff0-a31a-11e4-8c3c-b03e1bca500b.png)
