### ISSUE TITLE
System - Uploadtool Hierarchycache löschen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#25]
Bei jedem Updaten muss auch der Hierarchiecache gelöscht werden.

**Comment by marius300482** [comment]
Der Hierarchycache sollte nach einem Update ebenfalls gelöscht werden. Aber nur von der Institution die beteiligt ist. Hier kann wieder die InstitutionID genommen werden.

**Comment by rproutermedia** [comment]
Der Cache wird jetzt nach dem Update einer Institution gelöscht. 
Achtung: Für den Aufruf der Löschfunktion in VuFind muss die URL inklusive Domain (meta-katalog) in der ida-beans.xml hinterlegt werden.
