### ISSUE TITLE
System - Uploadtool Zip-Dateien

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#28]
.zip-Dateien können nicht eingespielt werden

"net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zul�ssig in Prolog."

**Comment by chboehm** [comment]
Neue Version deployed. Falls der Fehler noch auftritt, bitte überprüfen ob die richtige Institution gewählt ist.
