### ISSUE TITLE
Interface - [more] Funktionen reparieren core.phtml

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#3]
Mehrere Funktionen arbeiten noch nicht so, wie gedacht:

* Bei Autorinnen / Herausgeberinnen: die [mehr] Funktion lädt die Seite neu. Bitte nicht neu laden, sondern gleich zum "weitere Informationen" Tab springen.
* Bei Schlagworten: einklappen und ausklappen funktioniert nicht

**Comment by patrick-heiss** [comment]
Lieber Marius und lieber Christoph,

gerade habe ich die common.js aus unserem "meta-bootstrap3" Theme 
entfernt und kann sie jetzt direkt aus dem "bootstrap3" Theme laden. 
Dadurch sind u.A. die unten genannten JavaScript Fehler verschwunden und 
bestimmt auch einige weitere Fehler, die wir noch nicht entdeckt haben. 
=> Bitte updaten!

Läuft auf IDA1 die aktuelle Version? Dann würde ich meine Änderungen 
gleich mal auf dem gewohnten Weg einspielen.

Viele Grüße
Patrick

**Comment by patrick-heiss** [comment]
Erledigt!

**Comment by chboehm** [comment]
Ja, auf Ida1 läuft VuFind 2.3.1

**Comment by marius300482** [comment]
ich habe die Funktion gerade überprüft. Mit Chromium hat die Schlagwortfunktion noch nicht funktioniert: http://metadev.linuxx.org/Record/42490genderbib
Die Seite lädt auch immer noch neu, wenn ich auf weitere bei Autorinnen klicke:
http://metadev.linuxx.org/Record/29910genderbib

**Comment by patrick-heiss** [comment]
Jetzt verstehe ich welche Stelle du meinst. Ich hatte natürlich eine ganz andere Stelle untersucht. Ich kümmere mich darum.

**Comment by marius300482** [comment]
Entschuldige bitte die Ungenauigkeit meinerseits. Vielen Dank.

**Comment by patrick-heiss** [comment]
Bitte entschuldige, denn ich wollte mich gar nicht auf deine Beschreibung beziehen - die absolut richtig. Ich habe die Stelle mit einer anderen verwechselt und wollte nur sagen, dass ich dieses Ticket nicht einfach ohne zu testen geschlossen habe. :-)

Jedenfalls funktioniert jetzt beides unter den beiden Beispiel-URLs. Das more/less habe ich auch gleich mehrsprachig gemacht.

**Comment by marius300482** [comment]
Wunderbar!
