### ISSUE TITLE
Interface - Beschreibung in description.phtml

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#30]
Die Beschreibungstexte sollen die ganze Breite der Description einnehmen.

**Comment by marius300482** [comment]
Habe gerade noch eine Mail an Eva rausgeschickt. Bevor wir hier was machen, soll sie sich das nochmals ansehen und gucken ob es die beste Möglichkeit ist.

**Comment by marius300482** [comment]
Bitte so machen wie beschrieben!

**Comment by patrick-heiss** [comment]
Ist auch erledigt. Ich hoffe, dass ich die Beschreibunf richtig interpretiert habe.

**Comment by marius300482** [comment]
hast du! vielen Dank.
