### ISSUE TITLE
System - Uploadtool ida-beans.xml

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#31]
Diese Datei ist noch nicht im Git, oder? Ich kann sie nicht finden.

![meta_143](https://cloud.githubusercontent.com/assets/7677191/5919150/ce430ffc-a628-11e4-8107-fd7231bf54ae.png)

**Comment by chboehm** [comment]
Was suchst du? Den Ordner views oder die Datei web.xml? Beide sind da:

![github](https://cloud.githubusercontent.com/assets/5340686/5919343/3e70816a-a633-11e4-8f02-447e63362e5e.png)

**Comment by marius300482** [comment]
Ich suche die ida-beans-xml. Im Wiki steht hierzu diese Angabe:
/var/lib/tomcat7/webapps/meta-upload/WEB-INF/classes/spring/ida-beans.xml
Ich wollte gerne eine neue Institution anlegen.

**Comment by chboehm** [comment]
Ahh, dort liegt die Datei nach dem Deployment. In git liegt sie unter /meta-upload/src/main/resources/spring/

![beans](https://cloud.githubusercontent.com/assets/5340686/5919636/f929a2fa-a635-11e4-861e-6ce25ca91971.png)
