### ISSUE TITLE
System - Institution hinzufügen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#32]
* Zu ida-beans.xml folgendes hinzugefügt
```
<bean id="frauensolidaritaet" class="de.idadachverband.institution.IdaInstitutionBean">
        <constructor-arg index="0" value="frauensolidaritaet"/>
        <constructor-arg index="1" value="${xslt.basePath}/institution/frauensolidaritaet/gleich_frauensolidaritaet.xsl"/>
        <constructor-arg index="2" ref="xsltTransformer"/>
    </bean>
```
* Tomcat neugestartet (sudo service tomcat7 restart)
* Leider ohne Effekt

**Comment by chboehm** [comment]
Die Webapp muss neu gebaut und deployed werden. Am einfachsten ist es die Datei im git zu ändern. Dann geht sie beim nächsten Deployment nicht verloren. Und die Datei auf dem Server zu ändern: /var/lib/tomcat7/webapps/meta-upload/WEB-INF/classes/spring/ida-beans.xml und neu zu starten. Dann ist die Änderung sofort aktiv.

**Comment by marius300482** [comment]
Habe die Datei im Git und auf dem Server geändert. Jetzt funktioniert es.
