### ISSUE TITLE
Interface - Institutionskachel FFBIZ

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#35]
geht leider nicht.

**Comment by chboehm** [comment]
Hi Patrick,

mir ist die Ersetzung nicht klar:
        preg_replace("/[^0-9a-zA-Z_-öäüßÄÖÜ]/", "", $this->institutionId) . "_" . $this->language . ".ini";
Im Falle dieses Issues werden aus FFBIZ-Archiv_de.ini FFBIZArchiv.ini

Warum werden diese Zeichen ersetzt? 

Ich würde z.B. '../' ersetzen.

**Comment by patrick-heiss** [comment]
Hallo Marius,

jetzt habe ich [^0-9a-zA-Z_-öäüßÄÖÜ] durch [^0-9a-zA-Z_\-öäüßÄÖÜ] ersetzt. Damit ist ab jetzt auch das "-" erlaubt.

Bei der Erstellung eines Filters ist es in der Regel sicherer und einfacher, alle erlaubten Zeichen festzulegen, anstatt alle verbotenen. Denn im Zweifelsfalls ist der Filter besser ein wenig zu restriktiver, anstatt zahlreiche ungewollte Zeichen zuzulassen.
Zum Verständnis: Der Filter entfernt nun alle Zeichen, die nicht zu den folgenden gehören:
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZöäüßÄÖÜ_-"

Lediglich "../" und Leerzeichen zu ersetzen macht nur wenig Sinn, denn ../ kommt wohl in einem der Namen vor und die Sicherheit erhöht es auch nicht, weil aus "....//" nach einer Ersetzung wieder "../" werden würde...

**Comment by marius300482** [comment]
Was machen wir an dieser Stelle mit Institutionen die z.B. "Archiv der deutschen Frauenbewegung" benannt werden. Wie bekomme ich das Spatium hin? mit %20 dazwischen. Das %-Zeichen wäre ja nicht zugelassen.

**Comment by patrick-heiss** [comment]
Anstatt "Archiv der deutschen Frauenbewegung" einfach "ArchivderdeutschenFrauenbewegung"

**Comment by marius300482** [comment]
nein, braucht es nicht. Wenn ich weiß wie es geht, reicht das aus :)
