### ISSUE TITLE
Interface - Punkt statt Komma

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#37]
Derzeitig wird bei den Tausendern ein Komma verwendet. Hier soll aber ein Punkt hin:

So soll es sein: "Ergebnisse 1 - 20 von 158.044 für Suche"

So ist es derzeitig: "Ergebnisse 1 - 20 von 158,044 für Suche"

hier auch:

![meta_145](https://cloud.githubusercontent.com/assets/7677191/5997804/f013e03c-aab7-11e4-8336-9cdf69979898.png)

**Comment by patrick-heiss** [comment]
Ist erledigt.

number_format(VARIABLE)
durch 
number_format(VARIABLE, 0, ',', '.')
ersetzt

**Comment by marius300482** [comment]
sehr gut. danke
