### ISSUE TITLE
Interface - Cover & Schlagworte

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#38]
Bei Covern rücken die Schlagworte nach unten. Ist das so beabsichtigt (Bug oder Feature)

![meta_148](https://cloud.githubusercontent.com/assets/7677191/6019474/c8f1e300-ab98-11e4-8933-66a9a5eb3bb8.png)

**Comment by patrick-heiss** [comment]
Das war ein kleiner Bug. Ist jetzt behoben.

**Comment by marius300482** [comment]
sehr gut. Auch danke.
