### ISSUE TITLE
Feature - Daten von Institution aus Index löschen bei Update

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#4]
Bei jedem Update über das Updatetool müssen die alten Daten der betreffenden Institution vorher aus dem Core gelöscht werden.

**Comment by marius300482** [comment]
Dieses Feature hat oberste Priorität. Muss unbedingt alsbald in das Uploadtool integriert werden.

**Comment by marius300482** [comment]
@chboehm kannst du dich diesem Problem am Donnerstag annehmen?

**Comment by marius300482** [comment]
Gestern habe ich das Uploadtool herausgefordert. 4 Umwandlungen wurden eingestellt. Ausgeführt wurde aber nur eine.

**Comment by chboehm** [comment]
erledigt
