### ISSUE TITLE
Links in Ergebnisansicht für Autorin und Verfasserin falsch

### ISSUE THREAD

**Issue by chboehm** [marius300482/meta#41]
Die Links sollten eine erweiterte Suche in dem entsprechendem Feld ausführen und nicht auf Author/Home führen. Die Seite Author/Home ist in unserem Theme nicht umgesetzt.

**Comment by patrick-heiss** [comment]
Das ist nur ein Link von vielen, der nicht korrekt ist.
Siehe meinen Kommentar unter:  Feature - Personensuche #21 

Wir sollten zusammen alle "falschen" Links durchgehen, die zugehörige korrekte Suchanfrage definieren und nicht nach und nach für jeden Link ein weiteres Ticket auf machen. Das würde u.a. die Implementierung beschleunigen.

**Comment by patrick-heiss** [comment]
Die Templates sind soweit eingerichtet. Ich gebe das Issue an Christoph weiter, da anlog zu Issue #55 die Suche auf "allContributors" konfiguriert werden muss.

=> SIEHE Issue #55 (DUPLICATE)

**Comment by chboehm** [comment]
Searchfield allContributors in searchspec.yaml angelegt
