### ISSUE TITLE
Interface - Hierarchy funktioniert nicht

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#43]
Bei den Datensätzen aus Kassel funktioniert die Hierarchy leider nicht. Bitte nachsehen, welche Angabe noch fehlen. Mail mit den Datensätzen ist gerade raus.

**Comment by dkuom** [comment]
Hallo Marius,

anhand des XML fällt es mir schwer, das Problem zu identifizieren. Gut wäre hier zum Einen ein   beliebiger Vergleichsdatensatz (XML), der funktioniert. Vielleicht handelt es sich um ein strukturelles Problem. Zum Anderen könnte es nicht schaden, die Datensätze unter http://metadev.linuxx.org/ "live" zu sehen. Leider konnte ich sie dort nicht finden. Vielleicht stelle ich mich aber auch zu ungeschickt an.

VG

**Comment by marius300482** [comment]
Hallo Denny,
ich konnte die Problematik jetzt noch etwas eingrenzen. 

Bei den Akten funktioniert das mit der Hierarchie. Funktioniert heißt in diesem Fall, dass die entsprechenden Hierarchiepunkte aufklappbar sind.
http://metadev.linuxx.org/Record/43372addf

Bei den Hierarchiepunkten lässt sich hingegen nichts mehr aufklappen:
http://metadev.linuxx.org/Record/11BundesvorstandGeschaftsfuhrung_def_addf/

Die passende XML Datei hatte ich als Anhang mitgeschickt.

Vielleicht ein strukturelles Problem.

**Comment by marius300482** [comment]
Top-Datensatz
```
<field name="hierarchy_top_id">0Einleitung_es_addf</field>
<field name="hierarchy_top_title">Nachlass Elisabeth Selbert</field>
```
1 Hierarchiestufe
```
<field name="hierarchy_top_id">0Einleitung_es_addf</field>
<field name="hierarchy_top_title">Nachlass Elisabeth Selbert</field>
<field name="hierarchy_parent_id">0Einleitung_es_addf</field>
<field name="hierarchy_parent_title">Nachlass Elisabeth Selbert</field>
<field name="is_hierarchy_id">1PersonlicheUnterlagen_es_addf</field>
<field name="is_hierarchy_title">1 Persönliche Unterlagen</field>
<field name="hierarchy_sequence">1</field>
```
2 Hierachiestufe
```
 <field name="hierarchy_top_id">0Einleitung_es_addf</field>
<field name="hierarchy_top_title">Nachlass Elisabeth Selbert</field>
<field name="hierarchy_parent_id">1PersonlicheUnterlagen_es_addf</field>
<field name="hierarchy_parent_title">1 Persönliche Unterlagen</field>
<field name="is_hierarchy_id">11SchuleundStudium_es_addf</field>
<field name="is_hierarchy_title">1.1 Schule und Studium</field>
<field name="hierarchy_sequence">11</field>
```
3 Hierarchiestufe
```
<field name="hierarchy_top_id">0Einleitung_es_addf</field>
<field name="hierarchy_top_title">Nachlass Elisabeth Selbert</field>
<field name="hierarchy_parent_id">11SchuleundStudium_es_addf</field>
<field name="hierarchy_parent_title">1.1 Schule und Studium</field>
<field name="is_hierarchy_id">111SchuleundArbeitsverhaltnisse_es_addf</field>
<field name="is_hierarchy_title">1.1.1 Schule und Arbeitsverhältnisse</field>
<field name="hierarchy_sequence">111</field>
```
Aktenstufe
```
 <field name="hierarchy_top_title">Nachlass Elisabeth Selbert</field>
 <field name="hierarchy_top_id">0Einleitung_es_addf</field>
 <field name="hierarchy_parent_id">111SchuleundArbeitsverhaltnisse_es_addf</field>
 <field name="hierarchy_parent_title">1.1.1 Schule und Arbeitsverhältnisse</field>
 <field name="is_hierarchy_id">18856es</field>
 <field name="is_hierarchy_title">Schul- und Arbeitszeugnisse</field>
 <field name="hierarchy_sequence">Sch</field>
```

**Comment by dkuom** [comment]
Der zweitgenannte Link führt zu keinem Suchtreffer. Wurden die Daten wirklich komplett importiert?

**Comment by marius300482** [comment]
Ich habe ausversehen einen Slash hinter dem Link gemacht. So gehts:
http://metadev.linuxx.org/Record/11BundesvorstandGeschaftsfuhrung_def_addf

**Comment by marius300482** [comment]
#bump

**Comment by dkuom** [comment]
Bin dran.

**Comment by marius300482** [comment]
Wunderbar. Vielen Dank. Wollte nur sicher gehen, dass es nicht untergeht. LG Marius

**Comment by dkuom** [comment]
Hallo Marius,

nach serverseitiger Fehlersuche ohne Ergebnis habe ich nun herausgefunden, dass es sich um ein Darstellungsproblem handelt.
Lädt man die gleichen Seiten bspw. mit dem "genderbib" Theme, so werden Plus-Symbole zum Ausklappen der Unterbäume dargestellt. Dabei orientiert sich das Theme an der Eigenschaft "state" der jeweiligen Verzweigung im Baum. Klickt man auf das Plus-Symbol, wird der entsprechende Unterbaum nachgeladen.
Das "meta-bootstrap3" Theme verfolgt jedoch einen etwas anderen Ansatz, wonach ein Ein- und Ausklappen nur dort möglich ist, wo gemäß XML-Repräsentation ein Unterbaum vorliegt. Dies ist jedoch nur im "aktiven" Pfad der Fall. Denn genau darin liegt unsere Optimierung gegenüber früher. Es wird nur der gerade sichtbare Teilbaum geladen.

Ein Lösungsansatz wäre, das "meta-bootstrap3" Theme so anzupassen, dass es sich ebenfalls an "state" orientiert und Unterbäume nachgeladen werden können.

Was meinst du?


VG

**Comment by marius300482** [comment]
Hallo Denny,
dein Lösungsansatz klingt plausibel. Wie sieht es dann mit der Performance aus? 
Bitte so versuchen.

LG Marius

**Comment by dkuom** [comment]
Die  Performance hängt von der Größe des Unterbaums ab, ist aber i.d.R. recht gut (Antwortzeit <2s). Wenn du die Möglichkeit hast, kannst du dies im "genderbib" Theme testen.

Hinsichtlich der Umsetzung kann ich leider kein Versprechen abgeben, ob ich diese Woche noch damit beginnen kann.

**Comment by marius300482** [comment]
Dann machen wir es so, wie von dir vorgeschlagen. Gut wäre es wenn dieser Punkt bis Ende nächster Woche (27.02) umgesetzt ist. Reicht dir die Zeit?

**Comment by dkuom** [comment]
Ich denke das ist machbar!

**Comment by dkuom** [comment]
Hallo Marius,

habe soeben meine Änderungen committet. Sub-Bäume werden jetzt, wie im "genderbib" theme, nachgeladen. Bitte testen!


VG

**Comment by marius300482** [comment]
Lieber Denny,

ich konnte die Änderungen noch nicht sehen. In diesem Link lassen sich die anderen Bäume nicht laden:
metadev.linuxx.org/Record/12BeruflicheTatigkeit_es_addf/HierarchyTree?hierarchy=0Einleitung_es_addf&recordID=12BeruflicheTatigkeit_es_addf

Gucke ich an der falschen Stelle?

LG Marius


Von meinem Xperia™ Tablet gesendet

---- dkuom schrieb ----

**Comment by dkuom** [comment]
Nein. Ich hatte mich missverständlich ausgedrückt. Die Änderungen hatte ich lediglich zu Github committed. Patrick hat die Änderungen jetzt deployed. Bitte nochmals testen!

**Comment by marius300482** [comment]
Lieber Denny, 

jetzt passt es. Auf die schnelle konnte ich alles klicken. 

LG Marius 





Von meinem Xperia™ Tablet gesendet

---- dkuom schrieb ----
