### ISSUE TITLE
System - Uploadtool Fehler

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#44]
Zu wenig Speicher?!
de.idadachverband.transform.TransformedFileException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

**Comment by chboehm** [comment]
Ja, kann sein. Eigentlich möchte ich nicht zuviel Speicher vergeben, weil der Solr, Apache und OS auch welchen brauchen. Ich starte mal neu. Lass uns beobachten ob es reproduzierbar ist.
