### ISSUE TITLE
Interface - verschiedene Treiber verschiedene .phtml

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#45]
Ich wollte mich die nächsten Tage daran machen die Ausgabe an das Archivgut anzupassen. Dabei ist mir aufgefallen, dass ich zwar einen anderen RecordDriver habe aber die .phtml-Dateien die selben wären. Wir kann das geändert werden?

* library/description.phtml
* archive/description.phtml

**Comment by marius300482** [comment]
Das müssen wir uns am Mittwoch mal bitte ansehen. LG Marius

**Comment by chboehm** [comment]
Folgendes kann am record driver abgefragt erden:

`
<?php if ($this->driver->isLibrary()): ?>
Library Text
<?php endif; ?>
`
`
<?php if ($this->driver->isArchive()): ?>
Archive Text
<?php endif; ?>
`
`
<?php if ($this->driver->isSystematics()): ?>
Sytematics Text
<?php endif; ?>
`
