### ISSUE TITLE
Interface - neue Icons werden gebraucht

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#46]
Wir brauchen noch zusätzliche Icons.

* Plakate
* Nachlass / Vorlass
* Autograf
* Fotografien
* Buttons und Sticker
* Datenträger
* Ansichtskarte
* Bestandsübersicht (Frauennachlässe Wien)

**Comment by marius300482** [comment]
Mail an Eva ist raus!

**Comment by chboehm** [comment]
- Bestandsübersicht fehlt noch
- Titel in Liste entsprechen nicht Angabe in Solr
