### ISSUE TITLE
Interface - Institutionskachel auf rechter Seite

### ISSUE THREAD

**Issue by AnniQ** [marius300482/meta#47]
Ergebnisansicht: Wenn sich die Institutionskachel auf die rechte Seite verschiebt, verändert sich das Design.
richtig: http://metadev.linuxx.org/Record/8019ffbiz
falsch: http://metadev.linuxx.org/Record/7819genderbib

**Comment by patrick-heiss** [comment]
Die Kacheln sind derzeit in Reihen angeordnet, wobei sich jeweils 2 Kacheln in einer Reihe befinden. Daher entsteht im Moment zwangsläufig ungenutzer Platz, wenn zwei Kacheln nebeneinander angezeigt werden, die ungleich hoch sind und sich in der Reihe darunter weitere Kacheln befinden. Meinst du das mit "Design-Änderungen"?

Ich kann zugunsten des genutzten Platzes die Kacheln in Spalten anordnen. Das hat zur Folge, dass die Kacheln, die weiter unten kommen nicht mehr horizontal nebeneinander ausgerichtet werden können. Sobald die Kachel "Verfügbar in anderen Institutionen" hinzukommt, würde die "Institution" Kachel nicht mehr alleine dastehen und man hätte eine "saubere" horizontale Ausrichtung. Das ist Geschmackssache. Soll ich die Anordnung in Spalten umsetzen?

![metakatalog_ui-design_2014-11-17_4 detail](https://cloud.githubusercontent.com/assets/8044783/6128422/fa853186-b135-11e4-8030-6a8139ca4432.jpg)

**Comment by AnniQ** [comment]
Nein, mit "Design" gemeint war bloß die Schriftart, -größe und Zeilenabstände. Das wechselt, sobald die Kachel rechts steht, zur Schrift der "Dateninhalte".

**Comment by patrick-heiss** [comment]
Ahhh entschuldige, das habe ich bisher total übersehen.

**Comment by patrick-heiss** [comment]
Laut Wireframes ist die Version mit der "dünnen" Schrift die richtige. Daher habe ich diese jetzt auch für die Institution übernommen, wenn diese in der unteren Reihe steht.
