### ISSUE TITLE
Interface - Ergebnisliste bitte anpassen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#5]
Bitte folgendes in der Ergebnislistendarstellung ändern:

* von: (mit Doppelpunkt versehen)
* veröffentlicht: (klein und mit Doppelpunkt)
* max 20 Schlagworte (wenn mehr dann ein "weiter" Link der auf den Datensatz zeigt)
* max 5 Personen (wenn mehr dann ein "weiter" Link der auf den Datensatz zeigt)

**Comment by patrick-heiss** [comment]
Soll ich auch die Anzahl der Geografika limitieren? Das würde hinsichtlich der Implementierung keinen Mehraufwand bedeuten.

**Comment by patrick-heiss** [comment]
Mit den 4 Aufgaben bin ich jetzt fertig.

Abhängig Davon wie viele Geografika angezeigt werden sollen, kann die Zeile 87 der result-list.php angepasst werden: <? foreach(array("Topic" => 20, "Person" => 5, "Geo" => 9999) as $type => $limit): ?>

**Comment by marius300482** [comment]
Ich würde es erst mal so lassen. Wir werden in der Datenevaluation herausfinden, ob eine Begrenzung hier notwendig wird. 
Ich würde dich bitte die Änderungen auch im Wiki zu dokumentieren. Wo können welche Einstellungen vorgenommen werden.

**Comment by patrick-heiss** [comment]
Kein Problem, habe es im Wiki dokumentiert.

**Comment by marius300482** [comment]
Hier noch ein paar Ergänzungen:

* das von: bitte in Von: verwandeln
* Geografika aus der Ergebnisliste nehmen

**Comment by patrick-heiss** [comment]
Beides erledigt. :-)

**Comment by marius300482** [comment]
Sehr gut!
