### ISSUE TITLE
Interface - Institution mit Klammern ()

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#50]
Bei der Auswahl einer Insitution werden Klammern angezeigt. Lässt sich das ändern?

![meta_153](https://cloud.githubusercontent.com/assets/7677191/6129270/fa3492fe-b134-11e4-9130-9b61c3136748.png)

**Comment by patrick-heiss** [comment]
Das Problem ist jetzt behoben. Jetzt wied wieder eine Zahl angezeigt, wenn man in den Facetten etwas auswählt.

**Comment by marius300482** [comment]
wunderbar!
