### ISSUE TITLE
Interface - Enable translation function

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#51]
Für die Facetten wird an mehreren Stellen die Übersetzungsfunktion benötigt. Bitte implementieren.

**Comment by patrick-heiss** [comment]
Hier verstehe ich nicht genau was mit der Implementierung einer Übersetzungsfunktion gemeint ist. Die Facetten werden bei mir übersetzt (komplett auf deutsch) angezeigt und über die ini.Dateien im Verzeichnis "/usr/local/vufind2/languages" kann man sie in jede andere Sprache übersetzen.

Welche zusätzliche Funktion wird hier benötigt?

**Comment by marius300482** [comment]
@patrick-heiss du hast Recht. Hier funktioniert die Übersetzung. Aber was ist mit den Inhalten der Facette? Können diese auch übersetzt werden? Ich würde gerne mit der Benennung der Inhalte spielen wollen ohne gleich immer die ganze Transformation zu ändern.

Das gleiche Problem betrifft die Institutionsfacette. Hier kann es sein, dass irgendwann die Namen der Einrichtungen nochmal geändert werden (oder angereichert mit Standortangaben). Auch das will ich eigentlich nicht per Datentransformation ändern. Wäre zu aufwendig. 

![meta_160](https://cloud.githubusercontent.com/assets/7677191/6245589/3905ea18-b758-11e4-87b9-f54895bc4147.png)

**Comment by patrick-heiss** [comment]
Ich bin mit der Implementierung fertig und habe das Wiki entsprechend aktualisiert.

Absofort kann man die Inhalte von Facetten übersetzen. Dazu gibt man zuerst in der facets.ini die Facetten an, deren Inhalte übersetzt werden sollen und benutzt dazu einfach den Titel-Key der Facette. Anschließend kann man die Facetten-Inhalte ganz normal über die Übersetzungsdateien übersetzen:

In der facets.ini:

[Results]
typeOfRessource_facet = Typ
...

[TranslatedFacets]
facets[] = Typ
...

Falls die Gefahr zu hoch ist, dass die Übersetzung der Facetteninhalte sich mit den bestehenden Übersetzungen beißen, kann ich den Keys für die Facetteninhalte in den language.ini-Dateien noch ein Prefix voranstellen. Nachteil des Prefix: Man muss das Prefix beim Übersetzen kennen und muss es immer angeben. @Marius: Was ist dir lieber?

Beispiel ohne Prefix (aktuell):
ton=Ton

Beispiel mit Prefix:
facetEntry_ton=Ton

**Comment by patrick-heiss** [comment]
Erledigt!

Möglicher Änderungsvorhschlag mit Vor- und Nachteilen (siehe oben) kann noch umgesetzt werden.

**Comment by marius300482** [comment]
läuft!
