### ISSUE TITLE
Interface - Erweiterte Suche Felder löschen + hinzufügen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#53]
In der erweiterten Suche müssen Einträge gelöscht und hinzugefügt werden. So soll es dann aussehen:

* Titel
* Verfasst von
* Herausgegeben von
* Schlagwort
* ISBN/ISSN
* ZDB-ID (field name="zdbId")

![menu_155](https://cloud.githubusercontent.com/assets/7677191/6245187/c5b72c74-b753-11e4-8e3d-25a1372de91d.png)

Zur Orientierung:

![meta_157](https://cloud.githubusercontent.com/assets/7677191/6245297/0dba8b6e-b755-11e4-8e56-6be949de1e24.png)

**Comment by patrick-heiss** [comment]
In der Datei In der Datei /usr/local/vufind2/config/vufind/searches.ini muss die Advanced_Searches-Sesktion angepasst werden:

[Advanced_Searches]
AllFields           = adv_search_all
Title               = adv_search_title
Author              = adv_search_author
editorStr           = Editors
Subject             = adv_search_subject
ISN                 = adv_search_isn
zdbid               = ZDB-ID

Alle anderen Zeilen der Sektion müssen auskommentiert werden. Das Wiki habe ich entsprechend aktualisert. Jetzt fehlen nur noch Search-Handler. Bin dran.

**Comment by patrick-heiss** [comment]
Die obigen Änderungen wirken sich lediglich auf das UI aus. Vufind weiß im Anschluss noch nicht, wie es die neu hinzugefügten Eingabefelder verarbeitet werden sollen. Führt man z.B. eine Suche mit ZDB-ID aus, sucht Vufind derzeit noch über alle Felder.

Auf https://vufind.org/wiki/searches_customizing_tuning_adding wird auf die folgende Datei verweisen, in der man offenbar genau konfigurieren kann, wie sich die Suche verhält:/usr/local/vufind2/config/vufind/searchspecs.yaml

Christoph, wird sich ab jetzt darum kümmern.

**Comment by marius300482** [comment]
Okay wunderbar. So lange lasse ich der/die/das Issue offen.
