### ISSUE TITLE
Interface - Sortierfunktion abspecken

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#54]
Bei der Sortierfunktion müssen Punkte nur gestrichen werden.

![menu_156](https://cloud.githubusercontent.com/assets/7677191/6245247/78e69ee2-b754-11e4-8065-c7c9e9364842.png)

Zur Orientierung:

![meta_158](https://cloud.githubusercontent.com/assets/7677191/6245280/cf45be6c-b754-11e4-8b4a-8faf26268057.png)

**Comment by patrick-heiss** [comment]
Erledigt.

In der Datei /usr/local/vufind2/config/vufind/searches.ini muss die Sorting-Sesktion angepasst werden:

[Sorting]
relevance = sort_relevance
title = sort_title

Alle anderen Zeilen der Sektion müssen auskommentiert sein. Wiki ist ergänzt!

**Comment by marius300482** [comment]
tippi toppi - funktion überprüfe ich später. bis dahin closed
