### ISSUE TITLE
Interface - Links auf der Ergebnisseite anpassen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#55]
Auf der Ergebnisseite müssen die Links angepasst werden:

Pfeil 1 - Die Links bei den Autorinnen und Herausgeberinnen müssen im Feld "allContributors_facet" suchen (Dieses MultiValued-Feld wird gerade angelegt, muss also auch neu im Treiber angelegt werden)

Pfeil 2 -  Schlagworte: Löst eine Suche in Allfields aus

Pfeil 3 -  Personen: Löst eine Suche in Allfields aus

![meta_159](https://cloud.githubusercontent.com/assets/7677191/6245367/dcb00570-b755-11e4-88c2-14d84adf6043.png)

**Comment by patrick-heiss** [comment]
Die Links auf der Ergebnisseite sind die gleichen wie in der Detailansicht. Hierfür werden jeweils die Templates im folgenden Verzeichnis eingebungen, in denen die Such-URLs als Einzeiler definiert sind:
/usr/local/vufind2/themes/meta-bootstrap3/templates/RecordDriver/SolrIDA/

link-author.phtml <= "Verfasst von"
link-editor.phtml <= "Herausgegeben von"
link-geo.phtml <= BENÖTIGEN WIR VERMUTLICH NICHT
link-person.phtml <= "Personen"
link-subject.phtml <= BENÖTIGEN WIR VERMUTLICH NICHT
link-topic.phtml <= "Schlagworte"

Die Templates sind soweit eingerichtet. Ich gebe das Issue an Christoph weiter, da anlog zu Issue #41 die Suche auf "allContributors" konfiguriert werden muss.

**Comment by chboehm** [comment]
Searchfield allContributors in searchspec.yaml angelegt
