### ISSUE TITLE
Interface - Suchbegriffe behalten 

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#56]
Bei einer Suche wird der Suchbegriff / die Suchbegriffe aufgeführt können aber nicht einfach per Texteingabe erweitert werden. Für eben jene Erweiterung müssen derzeitig alle Informationen erneut in die Suchzeile eingegeben werden.

Darüber hinaus muss es noch eine Funktion geben das Suchfeld mit einem Klick zu leeren um neu zu suchen. Ich habe das mal versucht darzustellen. Hinsichtlich des Aussehens dieser Funktion braucht es noch weitere Absprachen mit Eva aber die können wir dann erst Anfang März machen. Die Funktion an sich will ich aber schon ausprobieren.
 
So solls aussehen:
![meta_162](https://cloud.githubusercontent.com/assets/7677191/6245805/33b7cdfe-b75a-11e4-808e-4f28f65fd2fb.png)

So sieht es derzeitig aus:
![meta_161](https://cloud.githubusercontent.com/assets/7677191/6245713/330fee1e-b759-11e4-85eb-c2a239953802.png)

**Comment by patrick-heiss** [comment]
Erledigt!

Die Änderungen waren weitreichender als gedacht, nun sollte es aber wie gewünscht funktionieren.

**Comment by marius300482** [comment]
Das sieht sehr gut aus. Genau so hatte ich mir das vorgestellt.
