### ISSUE TITLE
Interface - weitere Autorinnen in Ergebnisliste mit [weitere] kennzeichen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#57]
In der Ergbnisliste ist nicht sichtbar, dass es noch weitere Autorinnen gibt. Hier (also in der Ergebnisliste Bild1) sollte ebenfalls ein [weitere] stehen. 

![meta_163](https://cloud.githubusercontent.com/assets/7677191/6263794/bd02edae-b814-11e4-9566-d3a2b5ed0fce.png)
____________

![meta_164](https://cloud.githubusercontent.com/assets/7677191/6263799/cb37956e-b814-11e4-8a8f-843fc73f5943.png)

**Comment by patrick-heiss** [comment]
In der Ergebnisliste wird jetzt das [weiter] angezeigt, wenn es noch weutere Autorinnen gibt. Klickt man auf [weiter], gelangt man zur Detailansicht und landet gleich an der Stelle wo alle Autorinnen stehen.

**Comment by marius300482** [comment]
Bitte auch noch für die Herausgeberinnen machen. Da werden noch alle angezeigt. Danke.

**Comment by patrick-heiss** [comment]
Erledigt!
