### ISSUE TITLE
Interface - Formatfacette erst nach Typauswahl anzeigen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#60]
Die Formatfacette soll erst angezeigt werden, wenn die Nutzerin einen Typ ausgewählt hat.

**Comment by patrick-heiss** [comment]
Da die Facetten auf dem Preview-System ständig wechseln, möchte ich zur Sicherheit auch bei diesem Issue nachfragen.

Sobald in der Facette: 
```typeOfRessource_facet = Material zum ...```
ein oder mehrere Einträge ausgewählt wurden, soll die Facette
```format = Format```
sichtbar werden. Ist das Korrekt?

Werden die Facetten noch weiterhin wechseln? Dann baue ich ggf. noch einen zusätzlichen Check ein, der überprüft, ob die Typ-Facette überhaupt eingebunden ist. Anderenfalls würde die Format-Facette nicht mehr angezeigt werden...

**Comment by marius300482** [comment]
Die Nutzerinnen sollen erst auswählen können ob sie lesen, gucken oder hören möchten, wenn sie ihre Suche über die Facette einschränken. Wenn sie gewählt haben, können sie das Format auswählen, wie Artikel, Buch oder Plakat. Hier soll es auch keine Einschränkung über die Anzahl der angezeigten Formate geben. Es sollen immer alle angezeigt werden.

Vom Konzept würde das so aussehen:

* Typ auswählen
** Format auswählen

* Typ abwählen
** Alle Formate ebenfalls automatisch abwählen

**Erst Typ auswählen:**
![meta_165](https://cloud.githubusercontent.com/assets/7677191/6522139/1bd27f96-c3d9-11e4-8f9f-df026ba92840.png)
 
**Dann Format:**
![meta_166](https://cloud.githubusercontent.com/assets/7677191/6522153/2f78479c-c3d9-11e4-8369-a9ac5fbf07b7.png)

PS es handelt sich bei dieser Maßnahme um den Versuch die Nutzung der Kataloges zu steuern. Kann also sein, dass wir das wieder zurückbauen.

**Comment by patrick-heiss** [comment]
Erledigt! => Bitte testen und u.g. Frage beantworten

Lieber Marius, dieses Issue hat sich als wesenltich komplexer herausgestellt als erwartet. Daher habe ich zunächst eine ziemlich einfache, statische Lösung implementiert, die die Aufgabe wie oben beschrieben erfüllt. Sollte dir die implementierte Fuktionalität zusagen, werde ich zusätzlichen Aufwand betreiben und dabei die statische Version verbessern und die Abhängigkreit von Facetten über die facets.ini konfigurierbar zu machen. Bitte gib mir Bescheid, sobald es sicher ist, dass die Funktionalität auch in Zukunft verwendet wird oder nicht verwendet wird.

Als Resulatat davon könnte man nahezu beliebige Abhängigkeiten definieren, so dass z.B. erst Facette A sichbar ist, nach einer Auswahl auch Facette B, nach einer Auswahl in Facette B wiederum Facette C usw. Zudem stehen die Abhängigkeiten dann nicht mehr hartcodiert im Quellcode.

**Comment by marius300482** [comment]
Lieber Patrick, in der Arbeitsberatung mit Eva und Christoph haben wir das Feature bereits wieder beerdigt. Das hat mehrere Gründe: Zum einen ist die Nutzung fraglich und zum anderen ist das Konzept auch in der technischen Umsetzung zu kompliziert. Wir streichen dieses Feature also wieder. Kannst du es bitte wieder entfernen? LG Marius

ps. Trotzdem gute Arbeit :)

**Comment by patrick-heiss** [comment]
Erledigt!

Jetzt ist es wieder ausgebaut.

**Comment by marius300482** [comment]
wunderbar!
