### ISSUE TITLE
Interface - Sortierung "Neuste zuerst"

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#62]
In der Sortierfunktion muss es die Möglichkeit geben die neusten Dokumente zu erst anzeigen zu lassen. Bisher geht es nur in die andere Richtung.

**Comment by patrick-heiss** [comment]
Im Issue https://github.com/marius300482/meta/issues/54 habe ich "Nach Datum, absteigend" entfernt. Wird es jetzt doch wieder benötigt, oder ist das etwas anderes?

**Comment by marius300482** [comment]
Ich will gerne die Möglichkeit "Neuste Datensätze zuerst" anbieten. Mit den voreingestellten Sortiermöglichkeiten sind aber die Ergebnisse nicht wie erwartet. Hier werde ich heute nochmal mit Christoph sprechen auf welchem Feld da gesucht werden soll. Es kann sein, dass ich bei der Datentransformation noch etwas ändern muss, bis das so richtig funktioniert.

**Comment by chboehm** [comment]
Neueste zuerst wieder aktiviert. Das Feld publishDateSort mus befüllt werden.
