### ISSUE TITLE
Interface - Institutionskachel Infos über Karte

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#63]
Die Informationen zur Institution soll über der Karte plaziert werden. Das ist auch für die mobile Ansicht wichtig.

**Comment by patrick-heiss** [comment]
Erledigt!

Nur für den Fall, dass die Karte doch wieder oben stehen soll, notiere ich hier Änderungen, die dafür notwendig sind:

1. Verschiebe in der Datei view.phtml:
 ... 
direkt über:
<h5><?= $this->escapeHtmlAttr($institution); ?></h5>

Ersetze in der Datei _page-record.scss:
#map-canvas { margin: 20px 0;  }
durch:
#map-canvas { margin: -10px 0 20px }

**Comment by marius300482** [comment]
Danke für die Dokumentation. Ich habe es auch ins Wiki übertragen.
