### ISSUE TITLE
Interface - IE checken

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#64]
Wir haben die Rückmeldung bekommen, dass der IE nicht so richtig unterstützt wird.

**Comment by patrick-heiss** [comment]
Der IE ist immer ein heikles Thema.

Aber zuerst stellt sich jetzt die Frage, welche IEs wir unterstützen und welche wir explizit nicht unterstützen. Ich schlage den IE10 oder den IE9 als ältesten unterstützen Browser vor. Wenn wir noch den IE8 dazunehmen ist viel Zusatzaufwand notwendig, da dieser kein modernes JS und keine Mediaqueries versteht, weil er technisch gesehen aus der "Steinzeit" stammt. Dafür müssten wir viele technische Features nachrüsten. Der Aufwand steigt zudem nochmal ordentlich an, wenn wir auch noch den IE7 dazunehmen.

Auf den ersten Blick konnte ich im IE 10 keine gravierenden Fehler entdecken. Um Fehler reproduzieren und beheben zu können sind folgende Infos äußerst hilfreich:

- Welcher Fehler ist aufgetreten? (z.B. Tabs reagieren nicht auf Klicks)
- Auf welcher Seite tritt der Fehler auf? (z.B. Detailansicht, Ergebnisseite, Startseite, auf allen Seiten...)
- In welcher Auflösung tritt der Fehler auf? (z.B. 1024x768, 320x480, 1920x1080)
- Welcher IE wurde verwendet? (z.B. 8, 9, 10, 11)
- Welches Betriebssystem wurde verwendet? (XP, Vista, 7, 8)

**Comment by marius300482** [comment]
Hallo Patrick,
dein Vorschlag (IE 10 / IE 9) klingt sehr gut. Wenn wir sicher sind welche Browser von unserer Seite her richtig unterstützt werden, müssen wir noch einen Weg finden, diese Information auf der Webseite zu platzieren. Aber das bespreche ich dann bei unserem Treffen mit Eva.

Sind denn beide Browser schon soweit unterstützt, dass wir dieses Issue schließen können? Ich würde nur sehr ungern unnötig arbeit in die IE Kompatibilität stecken.

LG Marius

**Comment by patrick-heiss** [comment]
Ich werde virtuelle Maschinen mit jeweils einem "echtem" IE9 und einem IE10 aufsetzen und darauf ausgiebig testen. Sollten dir noch konkrete Fehler mitgeteilt werden, gib mir bitte über dieses Ticket Bescheid.

**Comment by marius300482** [comment]
Die Rückmeldung bisher lautete: "In MS Explorer, sehe ich nur ein langes Suchfeld und kann erweitert nicht anklicken"

**Comment by patrick-heiss** [comment]
Erledigt!

Im IE9 und IE10 sind mir beim Testen keine Fehler aufgefallen. Alle Ansichten, Suchfunktionen und auch die responsive Anpassung der Inhalte funktioniert problemlos. Solltest du noch Fehler finden oder sollten dir noch weitere Fehler mitgeteilt werden, bitte ich dich dafür jeweils ein neues Ticket zu öffnen.

**Comment by marius300482** [comment]
Vielen Dank. Wenn dir keine Fehler mehr aufgefallen sind, werde ich keine neuen Suchen. Erst wenn es Rückmeldungen gibt. LG Marius
