### ISSUE TITLE
Interface - Institutions.ini

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#65]
In der Institutionsini brauchen wir noch eine Angabe zum vollständigen, offiziellen Titel. Das würde ich gerne über die ini Datei machen, weil da Sonderzeichen vorkommen können.

name = 'STICHWORT Archiv der Frauen- und Lesbenbewegung, Bibliothek · Dokumentation · Multimedia'
address = 'Gusshausstraße 20/1A+B...';
addressExtra = 'Telefon: +43 (0)1 812 89 96...';
openingHours = '<strong>Öffnungszeiten</strong>...';

**Comment by patrick-heiss** [comment]
Das ist überhaupt kein Problem. Du kannst "name" jederzeit in jeder ini-Datei ergänzen. 

Ich vermute, dass deine Aufgabe noch weitergeht und "name" den bisher angezeigten Institutionsname in der Google Map Sprechblase und daunter ersetzen soll, aber nur gesetz dem Fall, dass "name" in der ini-Datei angegeben wurde. Richtig?

**Comment by marius300482** [comment]
richtig: wenn name angegeben ist, dann auch den Text in der Sprechblase ersetzen. 
Ich habe das jetzt mal für Stichwort probiert und "name" ergänzt aber in der Darstellung hat sich noch nichts geändert. Woran liegts?

**Comment by patrick-heiss** [comment]
Erledigt!

Meine Änderungen waren noch nicht comitted, weil ich deine Antwort abwarten wollte. Deshalb konntest du noch keine Änderungen sehen. Jetzt sind sie Änderungen sichtbar.
Durch die langen Instiutionsnamen gab es zu wenig Platz für die Sprechblase. Deshalb habe ich die Zoom-Controls der Google Map von links oben nach links unten verschoben, um ausreichend Platz zu schaffen.

**Comment by marius300482** [comment]
Das mit der Sprechblase ist natürlich ein Problem, wenn der Titel so lang ist. Aber wir lassen das erst mal genau so.
