### ISSUE TITLE
Interface - sourceInfo in result-list.phtml

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#67]
Die Sourceinfo soll bereits in der Ergbnisliste zu sehen sein. Unter Veröffentlicht muss dann noch "In: sourceInfo" stehen. Vielen Dank, ich habe es selber leider nicht hinbekommen. Warum auch immer.

**Comment by patrick-heiss** [comment]
Ich habe das "In:" eingefügt, indem ich den entsprechenden Code-Block aus der core.phtml-Datei in die result-list.phtml kopiert habe.

**Comment by marius300482** [comment]
Sehr gut.
