### ISSUE TITLE
Interface - Hierarchy Fehlersuche

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#68]
Hallo Denny,

die Hierarchy lässt sich nicht öffnen:
http://metadev.linuxx.org/Record/0502%C3%84ltesteBundesbriefehla 

obwohl es diese Akte hier mit Kontextbaum gibt:
http://metadev.linuxx.org/Record/BriefeverschiedenerPersonenundVerbandeandenBundundaneinzelneMitgliederdesBundes54hla

Kannst du mir weiterhelfen?

LG Marius

**Comment by dkuom** [comment]
Hallo Marius,

war ein ganz ähnliches Problem wie letzte Woche. Hatte mit dem Umlaut "Ä" am Beginn von "Älteste Bundesbriefe" zu tun. Habe ein Bugfix eingespielt/deployt. Kann getestet werden.


VG

**Comment by marius300482** [comment]
Super. Jetzt funktioniert es.
