### ISSUE TITLE
Interface - Thumbnailqualtität

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#7]
Die Qualität dieses Thumbnails ist schlecht:
http://metadev.linuxx.org/Record/56512fmt
Trotz ordentlicher Datei im Hintergrund:
http://metadev.linuxx.org/Cover/Show?size=large&contenttype=buch&isn=0812216733

Woran liegt das?

**Comment by patrick-heiss** [comment]
In der Detailansicht wird das Bild in "medium" geladen

http://metadev.linuxx.org/Cover/Show?size=**medium**&contenttype=buch&isn=0812216733
http://metadev.linuxx.org/Cover/Show?size=**large**&contenttype=buch&isn=0812216733

Kann ich das bedenkenlos auf "large" umstellen?

**Comment by marius300482** [comment]
ist es dann ratsam es auf medium zu lassen?

**Comment by marius300482** [comment]
http://metadev.linuxx.org/Record/27360fmt kein Thumbnail - kein Icon???

**Comment by patrick-heiss** [comment]
Das Problem liegt daran, dass beim Ausführen von "sudo ~/meta/deploy.sh" die "metadev-config.ini" mit "alten" Werten ausgeführt wurde. Jetzt habe ich die Werte im Git eingecheckt. Bitte nochmal probieren.

**Comment by patrick-heiss** [comment]
Den Code habe ich nun so abgeändert, dass jeweils das "large"-Bild verwendet wird und falls das nicht verfügbar ist, dann das "medium"-Bild. Im Cache-Verzeichnis habe ich mir die Bildgrößen der "large" Bilder angesehen und da diese nur wenige KB groß sind, könne sie bedenkenlos eingesetzt werden. 

Damit wird z.B. das oben angesprochene Thumbnail scharf dargestellt: http://metadev.linuxx.org/Record/56512fmt

**Comment by marius300482** [comment]
Vielen Dank, hat funktioniert.
