### ISSUE TITLE
Interface - Leere Suchen entfernen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#71]
Das Suchformular soll so eingestellt sein, dass leere Suchen nicht ausgeführt werden können.

**Comment by patrick-heiss** [comment]
Das Formular an sich kann grundsätzlich nicht verhindern, dass leere Suchen ausgeführt werden können. Wenn man diese URL im Browser eingibt, wird auch eine leere Suche ausgeführt, die komplett am Formular bzw. Frontend vorbeigeht: http://metadev.linuxx.org/Search/Results

Aber ich werde mit JS dafür sorgen, dass mindestens zwei Zeichen im Suchfeld angegeben werden müssen bevor der Browser das Formular absendet, wenn [Return] gedrückt oder [Suchen] angeklickt wird.

Genügt das, oder wird auch ein backend-seitiger Check/Schutz benötigt?

**Comment by marius300482** [comment]
Leere Suchen Bitte verunmöglichen, mindestens ein Zeichen muss eingegeben werden.  Bin gerade unterwegs deswegen so knapp in der Antwort.

**Comment by patrick-heiss** [comment]
Erledigt!

Nun sollte eine leere Suche weder im Frontend, noch direkt über das Backend möglich sein. Die minimale Länge habe ich an drei Stellen auf **1** Zeichen gesetzt.

Backend: 
/usr/local/vufind2/module/Ida/src/Ida/Controller/SearchController.php
Zeile 65: if ($this->isEmptySearch(**1**))

Frontend:
/usr/local/vufind2/themes/meta-bootstrap3/js/advanced_search.js
Zeile: 157: var minRequiredChars = **1**

/usr/local/vufind2/themes/meta-bootstrap3/js/meta.js
Zeile: 29: var minRequiredChars = **1**,
