### ISSUE TITLE
Interface - Sortierfunktion "Neuste Zuerst" einrichten

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#72]
Die Sortierfunktionen
* Neuste Zuerst (PublishDateMax)
* Älteste Zuerst (PublishDateMin)
einrichten.

Dikussion zum Thema: Datensätze ohne Jahresangabe werden in diesem Feld mit 0000 befüllt. Bei "Älteste Zuerst" würde man dann die ohne Jahresangabe finden. Vielleicht sollte die Sortierfunktion "Älteste Zuerst" gestrichen werden

**Comment by chboehm** [comment]
Kann in searches.ini deaktiviert werden.
