### ISSUE TITLE
Interface - Suchfunktion im Kontextbaum vereinfachen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#76]
Suchfunktion im Kontextbaum verändern. Das Dropdownmenü soll entfernt werden @patrick-heiss und die Suche nur auf dem Titelfeld @chboehm ausgeführt werden.

![meta_168](https://cloud.githubusercontent.com/assets/7677191/6635004/8b067abe-c958-11e4-96ea-b17e406820af.png)

**Comment by patrick-heiss** [comment]
Mein Part ist erledigt!

Ich habe das Dropdown gegen ein unsichtbares Feld ausgetauscht.
<input type="hidden" name="type" value="AllFields" id="treeSearchType" />

Für den zweiten Part der Aufgabe (s.o.) gebe ich das Issue an Christoph weiter.

**Comment by marius300482** [comment]
Erste Aufgabe ist durch. Was für @chboehm bleibt:

* Die Suche auf die Titelangabe beschränken.
