### ISSUE TITLE
Interface - Suchfunktion im Kontextbaum überarbeiten

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#77]
Nach einer Suche im Kontextbaum soll es eine Ergebnisliste im Kontextbaum geben. Die Ergebnissliste setzt sich aus Treffern zusammen wo der Suchbegriff im Titel zu finden ist. Die Titel die keinen Treffer haben, sollen ausgeblendet werden. Derzeitig bleiben immer alle stehen.

**Comment by dkuom** [comment]
Hi Marius,

zu deiner Info: ich habe heute begonnen den Task zu bearbeiten.


VG

**Comment by marius300482** [comment]
Hallo Denny,
habe gerade mit Christoph gesprochen. Bevor wir an dieser Stelle weitermachen, müssen wir erst gucken, wie viele Stunden noch übrig sind und was derzeitig Priorität hat. Diesen Task müssen wir noch verschieben.
LG Marius

**Comment by marius300482** [comment]
close
