### ISSUE TITLE
Interface - Ergebnisliste Herausgeberinnen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#8]
Wenn es keine Autorin zu einem Werk gibt, dann soll in der Ergebnisliste die Herausgeberin auftauchen. Aber nur wenn es keine Autorin gibt.

**Comment by patrick-heiss** [comment]
Ist implementiert! 

**Beispiel**:  Beim der Monographie "Frau : Realität und Utopie" wird nun "Herausgegeben von: Köppel, Christa; Sommerauer, Ruth" in der Ergebnisliste angezeigt, weil es keine Autorin ("Von:") gibt.

**Rückfrage**: Oben schreibst du "Autorin zu einem Werk"... Sind Collections auch Werke und gibt es dann überhaupt Autorinnen? Ich habe bisher noch keine Collection mit Autorinnen entdecken können, aber häufig werden dort Herausgeberinnen angezeigt. Daher kann ich pauschal für alle Collectrions die Herausgeberinnen anzeigen, falls vorhanden. Soll ich das tun, oder sind die Herausgeberinnen nur für nicht-Collections relevant?

**Comment by marius300482** [comment]
Implementierung habe ich gecheckt!

Zur Rückfrage: Was genau meinst du mit "Collections"? Sowas wie Sammelbände (z.B. http://metadev.linuxx.org/Record/47494fmt)?

**Comment by patrick-heiss** [comment]
Ja, Collections sind in VuFind, so etwas wie z.B. ein Sammelband. In der Regel erkennt man Collections daran, dass diese das Elternelement im "Context"-Baum sind.

Gerade habe ich mich mit Christoph abgesprochen und da wir nicht zwischen Collections und nicht Collections unterscheiden, wird die Herausgeberin überall dort angezeigt, wo es keine Autorin gibt. 

Damit sollte dieses Ticket ebenfalls erledigt sein.

**Comment by marius300482** [comment]
ja, ich denke auch.
