### ISSUE TITLE
Interface - Mobilansicht > automatisches Zuklappen der Kacheln 

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#80]
In der Mobilansicht klappen die Kacheln nach dem Aufklappen automatisch wieder zu. Der Fehler ist auf iOS (Safari) und Android (Chrome) reproduzierbar.

**Comment by patrick-heiss** [comment]
Erledigt!

Jetzt sollte es nicht mehr automatisch zuklappen.

**Comment by marius300482** [comment]
mit einem Android und einem IOS Gerät getestet. Läuft.
