### ISSUE TITLE
Interface - Mobilansicht > Sprungmarke 

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#81]
In der mobilen Suche kann man nach unten zu den Facetten springen über "Suche einschränken". Es gibt aber keine Möglichkeit wieder nach oben zu springen.

Hier bitte Rücksprache mit Eva halten. Es gibt mehrere Ideen, wie das umgesetzt werden könnte.

**Comment by marius300482** [comment]
#bump gibt es hier schon Neuigkeiten?

**Comment by patrick-heiss** [comment]
Erledigt!

**Comment by marius300482** [comment]
super
