### ISSUE TITLE
Interface - Anzahl vorgeschlagene Suchen im Suchschlitz verringern  

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#82]
Die Suchvorschläge sind derzeitig noch zu viel. Bitte auf 6 beschränken.

**Comment by patrick-heiss** [comment]
Erledigt!

Es werden jetzt nur noch die ersten 6 Vorschläge im Menü der Autocompletion angezeigt.

**Comment by marius300482** [comment]
Sehr gut. Kannst du im Wiki bitte noch dokumentieren, wo du die Anzahl eingestellt hast. Nicht, dass wir das wieder ändern müssen und nicht wissen wo. LG Marius

**Comment by patrick-heiss** [comment]
Erledigt!

**Comment by marius300482** [comment]
Traumhaft. Danke!
