### ISSUE TITLE
Interface - Leere Suchen mit unerwartetem Effekt

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#83]
Hallo Patrick, das Issue #71 ist soweit okay aber jetzt haben wir ein Problem:

Wenn die Daten umgewandelt sind, schicken wir eine Mail an die Institution um diese zu checken. Da leere Suche nun nicht mehr möglich sind können wir mit der passenden URL immer noch auf den Gesamtbestand der Einrichtung zugreifen:
* http://metadev.linuxx.org/Search/Results?lookfor=*&type=AllFields&filter%5B%5D=institution%3A%22schema+f%22 

Leider funktioniert das nur für die erste Seite. Bei der zweiten Seite wird dieser Link generiert:
* http://metadev.linuxx.org/Search/Results?type=AllFields&filter%5B%5D=institution%3A%22schema+f%22&page=2

Lässt sich das so ändern, dass eine Suche mit dem Sternchen so behandelt wird wie eine thematische Suche?

**Comment by patrick-heiss** [comment]
Aus dem Sternchen eine thematische Suche zu machen ist mit viel Aufwand sicherlich möglich, allerdings wäre das eine schlechte Lösung.

Als Zwischenlösung habe ich die Überprüfung jetzt so eingestellt, dass es genügt, wenn ein Suchstring eingegeben wurde oder/und eine Facette ausgewählt wurde (Wie es in http://metadev.linuxx.org/Search/Results?type=AllFields&filter%5B%5D=institution%3A%22schema+f%22&page=2 der Fall ist). Suchen werden demnach ausgeführt, wenn in der Such-URL "lookfor", "lookforX" oder "filter" vorkommt. Wobei X eine positive Ganzzahl ist.

Christoph wird mit dir noch über eine bessere Lösung diskutieren.

**Comment by marius300482** [comment]
wunderbar. Danke
