### ISSUE TITLE
Interface - Wording "Schlagworte" in der Ergebnisliste ändern

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#86]
Wording in der Ergebnisliste ändern. Aus Schlagworte wird "Weitere Suche mit"

**Comment by marius300482** [comment]
Dieses Wording aber bitte nur bei subjectTopic. Bei subjectPerson soll das derzeitige Wording beibehalten werden.

**Comment by patrick-heiss** [comment]
Erledigt!

In der Datei de.ini kannst du jetzt auch das Wording nach belieben verändern:
Subjects Geo = "Geografika"
Subjects Person = "Personen"
Subjects Topic = "Weitere Suche mit"

**Comment by marius300482** [comment]
Wunderbar!
