### ISSUE TITLE
System - batch-import-xsl.php mit Fehlermeldung

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#88]
Irgendwelche Ideen?

Processing /usr/local/vufind2/harvest/cid/1425294597_oai_lux_LUX01_000093202.xml ...
Fatal error: An exception was raised while creating "Solr"; no instance returned
Previous exception: An exception was raised while creating "VuFind\Logger"; no instance returned
Previous exception: "/var/log/vufind.log" cannot be opened with mode "a"
Previous exception: fopen(/var/log/vufind.log): failed to open stream: Permission denied

**Comment by chboehm** [comment]
Eventuell falsch gestartet?

```
sudo service vusfind start
```

**Comment by marius300482** [comment]
Tatsächlich hatte ich den Fehler auch, aber habe dann ordentlich auf meiner lokalen Maschine gestartet. Ich musste das Umwandlungsskript auch auf xslt 1.0 verändern. Am Ende blieben diese Fehler stehen. Müssen wir uns am Dienstag mal genauer ansehen. Bis dahin hat es Zeit

**Comment by marius300482** [comment]
Habe mich noch ein bisschen durchgearbeitet, erhalte jetzt aber einen "Fatal error: Read timed out after 30 seconds".
In der VuFind ausgabe steht "Caused by: java.net.SocketException: Datenübergabe unterbrochen (broken pipe)" und da endet auch mein Latein. Müssen wir am Dienstag mal angehen.

**Comment by chboehm** [comment]
Liegt an langsamen commit mit optimize. Nie optimize und commit nur bei vielen Dokumenten.
