### ISSUE TITLE
Interface - result_list überarbeiten

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#89]
title_short : title_sub
Verfasst von: Nachname, Vorname [weitere]
Herausgegeben von: Namensangabe [weitere] #wenn keine Autorinnenangabe
In: sourceInfo
Verlag, Jahr #displayPublishDate / Heft #issue Band: volume, physical, isbn/issn
Weitere Suchen: topic #86 
Personen: subjectPerson

Bitte darauf achten, dass alle Informationen in neue Zeilen kommen und das keine Lücken entstehen, wenn eine Information fehlt.

**Comment by patrick-heiss** [comment]
Gerade habe ich bemerkt, dass es ungültige, leere Einträge in der Datenbank gibt, die zu Lücken in der Frontend Darstellung führen.
Beispiel: 
![ungueligereintrag](https://cloud.githubusercontent.com/assets/8044783/7047861/a6d49e58-de0f-11e4-9861-c22606af9f30.png)
Sobald diese leeren Einträge in der Datenbank entfernt werden, werden sie auch nicht mehr im Frontend angezeigt.

**Comment by marius300482** [comment]
Ja, diese leeren Einträge müssen wir noch beseitigen oder reparieren.

**Comment by patrick-heiss** [comment]
Erledigt!

Bitte schau dir insbesondere die folgende Zeile an, ob alles vorhanden ist:
"Verlag, Jahr #displayPublishDate / Heft #issue Band: volume, physical, isbn/issn"

Ich habe die Funktionen  "getCleanISSN() und getCleanISBN() genommen, um die ISBN und ISSN auszulesen. Bitte gib mir Bescheid, falls das Ergebnis von deinen Erwartungen abweicht.

**Comment by marius300482** [comment]
Auch das gucke ich mir in der nächsten Woche genauer an. Ich bin mir noch nicht sicher wo die letzten Angaben in deinem Kommentar stehen sollten. Bei TimeSpanStart bin ich mir aber ganz sicher, dass es nicht mehr auftaucht. Hier wurde das System für die Datumsangabe verändert.
