### ISSUE TITLE
Interface - Ergebnisliste timeSpan

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#9]
In der Ergebnisliste werden die Angaben timeSpan nicht berücksichtigt. Hier wird bisher nur das publishDate ausgegeben.

**Comment by patrick-heiss** [comment]
Erledigt!

Jetzt wird z.B. für den Titel "Die Frau in unserer Zeit" die Zeitspanne "Zeitspanne: 1992 - 1999" angezeigt.

**Comment by marius300482** [comment]
Sehr gut!
