### ISSUE TITLE
Interface - core.phtml überarbeiten

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#90]
title_short : title_sub
Verfasst von: Nachname, Vorname [weitere]
Herausgegeben von: Namensangabe [weitere] #wenn keine Autorinnenangabe
In: sourceInfo
Verlag, Jahr #displayPublishDate / Heft #issue Band: volume, physical

danke.

**Comment by patrick-heiss** [comment]
Erledigt!

Hier bitte ebenfalls überprüfen, ob alles korrekt angezeigt wird, insbesondere die Zeile:
"Verlag, Jahr #displayPublishDate / Heft #issue Band: volume, physical"

Im Gegensatz zu den Suchtreffern soll hier das Label "Veröffentlicht:" und die ISBN/ISSN nicht angezeig werden. Ist das korrekt?

**Comment by marius300482** [comment]
Ja, genau. Hier soll die ISBN nicht stehen. Weil die ja in der description.phtml schon auftaucht. Alle Angaben werde ich mir im Laufe der nächsten Woche ansehen. Und dann, wenn nötig, ein neues Issue eröffnen. Bis dahin erst mal vielen Dank!
