### ISSUE TITLE
Interface - Ähnliche Einträge Titelfeld

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#91]
Bei den "Ähnlichen Einträgen" wird wahrscheinlich nur der title_short angezeigt. Das ist bei Dokumenten (meist Zeitschriftenhefte) die einen gleichen Titel haben, leider etwas verwirrend. Bitte hier das title feld auslesen lassen.

**Comment by patrick-heiss** [comment]
In der Similar.phtml Datei wird der Titel standardmäßig mit "$data->getTitle()" ausgegeben. Das ist offenbar korrekt.

Kannst du bitte ein Beispiel nennen, bei dem ein zu kurzer Titel angezeigt wird?

**Comment by patrick-heiss** [comment]
...

**Comment by marius300482** [comment]
hier ist ein gutes Beispiel, wie ähnliche Einträge nicht so viel Sinn machen:
http://metadev.linuxx.org/Record/1094kfgv
Wahrscheinlich wäre es da am sinnvollsten, immer gleich den Standort anzuzeigen. So als Idee.

**Comment by patrick-heiss** [comment]
Meinst du mit "Standort" getDisplayPublicationDate (Erscheinungsdatum), getIssues (Heftnummer) und getVolumes (Band-Nummer), oder ist "Standort" ein Solr Attribut, dass wir unter http://metadev.linuxx.org/Record/1094kfgv nicht anzeigen?

**Comment by marius300482** [comment]
Mit Standort meinte ich die besitzende Einrichtung.

**Comment by patrick-heiss** [comment]
Dabei fällt mir auf, dass z.B. es im FrauenMediaTurm dutzende Zeitschriften gibt, die exakt den gleichen Titel tragen. Das würde das Problem der gleichen Titel in der rechten Spalte kaum lösen, da sich alle Zeitschriften mit dem selben Titel in der selben Einrichtung befinden können.

Falls das keine Rolle spielt, werde ich den Namen der Einrichtung natürlich gerne hinzufügen.

**Comment by marius300482** [comment]
Weitere Informationen, wie von dir vorgeschlagen (Erscheinungsdatum & Heftnummer) sowie der Name der Einrichtung wäre doch gut!

ps. Es ist so schade, dass du gehst!
