### ISSUE TITLE
Interface - Startseite überarbeiten

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#94]
Bitte alle nötigen Informationen bei Eva einholen.

**Comment by patrick-heiss** [comment]
Erledigt!

Solltest du nach längerer Zeit noch eine Kleinigkeit finden, dann öffne bitte ein neues Ticket, da dieses Issue insgesamt sehr groß ist.

**Comment by marius300482** [comment]
mache ich. vielen Dank!
