### ISSUE TITLE
Interface - Layout Seitentitel mit Ergebnisanzeige

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#96]
Hier soll der Text nach einer Suche geändert werden. Weitere Informationen bei Eva.
 
![auswahl_176](https://cloud.githubusercontent.com/assets/7677191/7136447/9662eca6-e2a0-11e4-8421-42499d399332.png)

**Comment by patrick-heiss** [comment]
Erledigt!

**Comment by marius300482** [comment]
Wunderbar
