### ISSUE TITLE
Interface - Aufklappen der Facette „Beteiligte Personen“

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#97]
Hier soll es eine weitere Funktion geben: Alle anzeigen lassen. Alle "Beteiligten Personen" sollen dann alphabetisch geordnet sein. Auch hier gibt es weitere Informationen von Eva.

**Comment by patrick-heiss** [comment]
Erledigt!

Ich habe als Limit 9999 Personen eingestellt, weil die Seitenanfrage abschmieren würde wenn wir noch mehr Einträge anfordern. Da die Einträge nach Häufigkeit sortiert, sind sollten 500 Seiten zum stöbern ausreichen.

**Comment by marius300482** [comment]
Kannst du die Einträge auf alphabetisch ordnen?

**Comment by patrick-heiss** [comment]
Ja, kann ich machen.

**Comment by patrick-heiss** [comment]
Erledigt!
