### ISSUE TITLE
Interface - Checkbox an der Suche

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#98]
Es soll eine Checkbos neben der Suche geben, mit der die Suchfilter "sticky" gemacht werden können. Weitere Informationen von Eva.

**Comment by patrick-heiss** [comment]
Wenn Facetten ausgewählt sind und sticky bleiben, werden in den meisten Fällen beim Ändern der Suchwörter keine Treffer mehr angezeigt, was die Benutzer*innen irritieren kann. Ich möchte mit Eva hierzu noch die bestmögliche Lösung besprechen.

**Comment by marius300482** [comment]
#bumb gibt es hier schon was Neues?

**Comment by marius300482** [comment]
Siehe Mail.

**Comment by marius300482** [comment]
**Frage**: Soll es die Checkbox "Mit Einschränkung suchen" auch bei der erweiterten Suche geben? 
**Antwort**: Wenn nur die Institution sticky sein soll und eine entsprechende Ceckbox neben der Institutionsangabe steht, dann bleibt sie bei beiden suchen sticky. 

![auswahl_181](https://cloud.githubusercontent.com/assets/7677191/7856563/a1a05d56-0519-11e5-81f9-8341b169543a.png)

**Frage**: Und falls "ja", soll die Checkbox der einfachen Suche mit der Checkbox der erweiterten Suche synchronisiert werden? D.h., dass sie im jeweils anderen Suchformular automatisch mit-gesetzt/mit-entfernt wird. 
**Anwort**: Ja, es soll sich auf beide Suchen auswirken, wenn die Checkbox ein- oder ausgecheckt wird

**Frage**: Soll die Checkbox nach einer "Sticky Suche" weiterhin gesetzt bleiben, oder muss sie vor jeder "Sticky Suche" erneut angeklickt werden? 
**Anwort**: Eine Suche = eine Session. Während dieser Suche bleibt es sticky. Wird die Seite nach extern verlassen muss neu sticky gemacht werden. Wird sich innerhalb von META bewegt bleibt es sticky.

**Frage**: Soll die Checkbox dauerhaft gemerkt werden, damit die zuletzt ausgewählten Facetten automatisch wiederhergestellt werden, wenn die Benutzer*innen z.B. auf eine andere Seite (z.B: Tag-Cloud) oder auf eine andere externe Seite (z.B. Google) wechseln und dann zu den Suchergebnissen zurückkehren? 
**Antwort**: Wer die Seite verlässt muss neu sticky machen. Wer bleibt (auch Tag-Cloud) bleibt sticky.

**Comment by marius300482** [comment]
Hier bitte hier den Original "Behalte die Filtereinstellungen" wieder einbauen. Wie bei der Genderbibliothek. Ich habe das Gefühl, dass das schneller zu lösen ist als nur die Institutionen sticky zu machen. Den einzigen Unterschied hätte ich gerne in der Position. Bei voller breite sole
 
![auswahl_239](https://cloud.githubusercontent.com/assets/7677191/8590807/5354881e-2613-11e5-9bd2-83166c1a3efd.png)

![auswahl_240](https://cloud.githubusercontent.com/assets/7677191/8590909/282e106e-2614-11e5-8dd0-23a46efa5ec9.png)

**Comment by marius300482** [comment]
![auswahl_248](https://cloud.githubusercontent.com/assets/7677191/8615177/0688b6b8-26e0-11e5-89d7-30aeb006aa74.png)

![auswahl_247](https://cloud.githubusercontent.com/assets/7677191/8615188/2521ba16-26e0-11e5-8a98-f1ce606a45fe.png)

Sowas könnte ich mir vorstellen.

**Comment by marius300482** [comment]
#bump wie sieht es hier aus. Irgendwelche Ideen, ob dieses Feature bald kommt. Oder kümmert sich Denny?

**Comment by rproutermedia** [comment]
Ich bin gerade damit beschäftigt, das entsprechende Vufind-Feature zu re-aktivieren. Im Default-Theme funktiniert es, in meta-bootstrap3 noch nicht.

**Comment by rproutermedia** [comment]
Ich habe die "Behalte die Filtereinstellungen" Checkbox wieder aktiviert. Das Design würde ich gern Denny überlassen, der nächste Woche wieder hier ist.

**Comment by marius300482** [comment]
So machen wir es!

**Comment by marius300482** [comment]
Wir haben das Konzept überarbeitet. Die "Checkbox" soll über den Suchfiltern (aka Facetten) stehen. 
* Wird eine Suche ausgeführt - ist der Schalter aus.
* Wird eine Ergebnisliste gefiltert - ist der Schalter an und bleibt an. 

Filter an
![filter_an](https://cloud.githubusercontent.com/assets/7677191/8719316/498c910a-2b9a-11e5-9215-d72b7430a48b.png)

Filter aus
![filter_aus](https://cloud.githubusercontent.com/assets/7677191/8719318/4d9a3b9e-2b9a-11e5-81f6-21e703a7c698.png)

Gesamtdarstellung
![filter_an_large](https://cloud.githubusercontent.com/assets/7677191/8719321/50dae33a-2b9a-11e5-8594-2099253153e7.png)

**Comment by rproutermedia** [comment]
Momentan wird der Schalter nur eingeblendet, wenn tatsächlich Filter gesetzt wurden, da er sonst keinen Sinn ergibt.

Ich kann gerne noch einmal mit Eva darüber sprechen, aber ich finde der Schalter sollte weiterhin mit "Filter behalten" o.ä. gelabelt werden, um NutzerInnen nicht zu verwirren. Er schaltet ja nicht die Filterung ein oder aus, sondern sorgt dafür, dass die Filter auch bei zukünftigen Suchen erhalten bleiben.

**Comment by marius300482** [comment]
Das mit den Filtern, dem Konzept dahinter und der richtigen Positionierung ist tatsächlich ein schwieriges Thema. Besonders, wenn wir die mobile Ansicht mittdenken.

Du hast recht, das "Filter an" Teil erscheint erst, wenn eine Filter (aka Facette) ausgewählt wurde. Wenn ich ihn deaktiviere dann "Filter aus". Die Darstellung ohne Filter an/aus-Schalter fehlt noch.
Die Positionierung finde ich dennoch richtig, weil gleich bei den Suchfiltern und weil sehr deutlich zu sehen.

Was wir bei unserer Planung mitgedacht haben waren folgende Punkte.
* Das mit dem Filtern ist gar nicht so einfach zu verstehen. Filter gehen aber besser als Facetten oder Sucheinschränkungen.
* Um eine Filterung deutlich zu machen braucht es visuelle Hilfe. Da es derzeitig kein passendes Icon gibt (das Filtericon lehne ich ab) ist ein an/aus-Schalter mehr als verständlich. Mit den Titel "Ergebnis filtern" soll klar werden "an/ja - Ergebnisse filtern" und "aus/nein - nicht mehr Ergebnisse filtern"
* Dieses Konzept lässt sich auch in der mobilen Ansicht umsetzen, in der noch weniger Platz ist und es trotzdem nachvollziehbar dargestellt werden soll.

Das mit dem Lable "Filter behalten" sehe ich anders. Die Facetten bleiben farbig markant sichtbar. Ändere ich meine Suche bei aktivierten Filtern, bleiben die Filter stets markant blau. Es gibt diese eine Schwelle, bei der die Nutzerinnen diesen Teil lernen müssen, dass das zusammenhängt, dann ist alles in Butter. Das Lable braucht es hierfür nicht zwangsläufig.

**Comment by marius300482** [comment]
Szenario

1. Ich suche und bekomme eine Ergebnisliste -> kein Filter an Knopf zu sehen
2. Ich filtere mit einem Suchwort -> Der "Filter an" Knopf erscheint
3. Ich suche weiter mit einem weiteren Suchwort -> Filter bleiben erhalten, weil "Filter an"
4. Ich schränke weiter ein mit Filter ->  Filter bleiben erhalten, weil "Filter an"
4. Ich will die Filter ausschalten und drücke den "Filter an" Knopf - der Regler geht zur Seite zu "Filter aus"
5. Die Seite lädt neu und ich bin wieder auf dem Stand von Punkt 1 -> Ergebnisliste ohne "Filter an Knopf"

**Comment by marius300482** [comment]
Jetzt nochmal überarbeitet. Die "Filter AN" Angabe ist jetzt hoch in die Suchleiste gerückt und wurde über den Facetten entfernt. 

**Filter aus:**
![filter_aus_web](https://cloud.githubusercontent.com/assets/7677191/8746596/9582898a-2c7a-11e5-9037-df37473a6ef2.png)


**Filter an:**
![filter_an_web](https://cloud.githubusercontent.com/assets/7677191/8746587/6fc7ce9e-2c7a-11e5-89f3-7f240a9c70ee.png)

**Comment by dkuom** [comment]
Hallo Marius,

funktional ist alles umgesetzt. Was das Design angeht, möchte ich am Montag noch einmal mit  Eva sprechen. Kann aber soweit getestet werden.


VG

**Comment by marius300482** [comment]
Endspurt Issue. Ich bin mit der Funktionalität sehr zufrieden. Es ist so wie beschrieben. Jetzt noch die Umsetztung fürs Design und dann haben wir es.

**Comment by marius300482** [comment]
Gibt es schon Pläne wann die letzten Arbeiten umgesetzt werden können?

**Comment by dkuom** [comment]
Nein, Marius. Eva war heute nicht im Büro. Ich werde morgen diesbzgl. auf sie zugehen.

**Comment by marius300482** [comment]
Lieber Denny, vielen Dank für die schnelle Info. Ich hoffe also auf morgen 😊

**Comment by chboehm** [comment]
Lieber Marius,

wir haben das nochmal gemeinsam durchdacht. Geht es vor allem darum, dass es einen dauerhaften Filter auf eine Institution geben soll?

Grüße
Christoph

**Comment by marius300482** [comment]
Hallo Christoph, es geht darum das die jetzige Filter Möglichkeit an das Design angepasst wird. Mit der derzeitigen Funktion bin ich voll zufrieden. 

Das mit den Institutionen und dem Filter ist schon vor einer ganzen Weile fallen gelassen worden. Wegen nicht sinnvoll. Die derzeitige Filterfunktion soll so bleiben und gestalterisch angepasst werden.

**Comment by marius300482** [comment]
Gibt es schon einen Plan wann ich mit der Gestaltung des Filters rechnen kann? LG Marius

**Comment by dkuom** [comment]
Hallo Marius,

die Checkbox in neuem Design steht jetzt zur Verfügung. Bitte testen!


VG

**Comment by marius300482** [comment]
Find ich gut so. Macht was es soll und ich bin glücklich. Vielen Dank.
