### ISSUE TITLE
Interface - ausgewählte Schlagwörter untereinander anordnen

### ISSUE THREAD

**Issue by marius300482** [marius300482/meta#99]
Wenn Schlagwörter in der Facette ausgewählt werden, dann erscheinen sie untereinander. Hinter jedem Schlagwort gibt es einen Link mit dem eine breite Suche ausgelöst wird. Weitere Informationen gibt es bei Eva.

**Comment by patrick-heiss** [comment]
Erledigt!

**Comment by marius300482** [comment]
sehr gut!
